schema_version = 1

[app]
id = "font_cantarell_regular"
kind = "file"
role = "asset"

[source.file]
path = "userland/fonts/Cantarell-Regular.capfont"

[build]
format = "blob"
target = ""
optimize = "release"
output_name = "CANTREG.CFNT"
strip = false

[[publish]]
id = "rootfs"
fs = "rootfs"
path = "/share/fonts/Cantarell-Regular.capfont"
