schema_version = 1

[app]
id = "zlib"
kind = "file"
role = "service"

[source.file]
path = "userland/fixtures/libz.so.1"
rebuild_tool = "wsl"
rebuild_dir = "."
rebuild_args = ["-e", "bash", "tools/build_wsl_zlib.sh"]

[build]
format = "blob"
target = ""
optimize = "release"
output_name = "LIBZ.SO.1"
strip = false

[[publish]]
id = "rootfs-soname"
fs = "rootfs"
path = "/lib/libz.so.1"

[[publish]]
id = "rootfs-linker"
fs = "rootfs"
path = "/lib/libz.so"
