schema_version = 1

[app]
id = "pitty"
kind = "cargo"
role = "app"

[source.cargo]
manifest = "user/rust/Cargo.toml"
package = "pitty"
bin = "pitty"
target = "x86_64-unknown-none"
target_dir = ".artifacts/cargo-target"

[build]
format = "pie-elf"
target = "x86_64-unknown-none"
optimize = "release"
output_name = "PITTY.ELF"
strip = true

[[publish]]
id = "rootfs"
fs = "rootfs"
path = "/cmd/pitty.elf"
