schema_version = 1

[app]
id = "ld"
kind = "zig"
role = "service"

[source.zig]
entry = "userland/programs/ld.zig"
module = "abi_root"

[build]
format = "pie-elf"
target = "x86_64-freestanding-none"
optimize = "ReleaseSmall"
output_name = "LD.ELF"
strip = true

[[publish]]
id = "rootfs"
fs = "rootfs"
path = "/lib/ld.so"

[[publish]]
id = "bootfs"
fs = "bootfs"
path = "/lib/ld.so"

