schema_version = 1

[app]
id = "pachaland"
kind = "cargo"
role = "service"

[source.cargo]
manifest = "userland/pachaland/Cargo.toml"
package = "pachaland"
bin = "pachaland"
target = "x86_64-unknown-none"
target_dir = ".artifacts/cargo-target"

[build]
format = "pie-elf"
target = "x86_64-unknown-none"
optimize = "release"
output_name = "PACHALND.ELF"
strip = true

[[publish]]
id = "rootfs"
fs = "rootfs"
path = "/srv/pachaland.elf"

[[publish]]
id = "bootfs"
fs = "bootfs"
path = "/srv/pachaland.elf"
