[package]
name = "rust_wasmtime_host_demo"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "rust_wasmtime_host_demo"
path = "src/main.rs"

[dependencies]
rt_alloc = { path = "../../../user/rust/rt_alloc" }
rt_core = { path = "../../../user/rust/rt_core" }
wasmtime_host = { path = "../../../user/rust/wasmtime_host" }
