[workspace]
members = [
    # Runtime substrate
    "rt_core",
    "rt_alloc",
    "rt_handle",
    "rt_io",

    # Public facade
    "cap_std",

    # Wasmtime support
    "rt_wasmtime_platform",
    "wasmtime_config",
    "wasmtime_host",

    # Runtime / cap_std demos
    "rust_hello",
    "rust_fs_demo",
    "rust_fs_mut_demo",
    "rust_open_exec_demo",
    "rust_spawn_demo",
    "cap_std_child_exit_demo",
    "cap_std_exec_demo",
    "cap_std_fs_demo",
    "cap_std_wait_demo",

]
resolver = "2"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = "z"
lto = false
codegen-units = 1
strip = "symbols"
