package livebootfs

import (
	"bytes"
	"compress/zlib"
	"crypto/sha256"
	"debug/elf"
	"encoding/base64"
	"encoding/binary"
	"encoding/hex"
	"fmt"
	"io"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"

	"capabilityos/pack/internal/bootfs"
	"capabilityos/pack/internal/buildsys"
	"capabilityos/pack/internal/config"
	"gopkg.in/yaml.v3"
)

const (
	SpecPath     = "pack/live-bootfs.yaml"
	OutputDir    = ".artifacts/live-bootfs"
	ManifestName = "bootfs.generated.txt"
	ImageName    = "BOOTFS.IMG"
	// Limine boot copies INITAPP.ELF and the archive into this same kernel scratch.
	// Keep this in sync with kernel/src/boot/boot_scratch.zig.
	bootScratchBytes = 32 * 1024 * 1024
	maxLiveRootBytes = 64 * 1024 * 1024
	// A content header identifies a packed inner bootfs independently of its
	// archive pathname. The following uint64 is the expanded byte count.
	packedRootMagic = "PACHAZ1\x00"
)

type Spec struct {
	Schema int               `yaml:"schema"`
	SHA256 map[string]string `yaml:"sha256"`
	Files  map[string]string `yaml:"files"`
}

type Options struct {
	NoBuild            bool
	AuthorizedKeysPath string
}

type Result struct {
	Manifest string
	Image    string
	Entries  int
	Bytes    int64
}

func LoadSpec(filename string) (Spec, error) {
	data, err := os.ReadFile(filename)
	if err != nil {
		return Spec{}, err
	}
	var spec Spec
	decoder := yaml.NewDecoder(bytes.NewReader(data))
	decoder.KnownFields(true)
	if err := decoder.Decode(&spec); err != nil {
		return Spec{}, fmt.Errorf("live bootfs spec: %w", err)
	}
	if spec.Schema != 1 || len(spec.Files) == 0 {
		return Spec{}, fmt.Errorf("live bootfs spec: unsupported schema or empty files")
	}
	for destination, appID := range spec.Files {
		if destination == "/" || !strings.HasPrefix(destination, "/") ||
			path.Clean(destination) != destination || strings.ContainsAny(destination, "=\n\r") ||
			appID == "" {
			return Spec{}, fmt.Errorf("live bootfs spec: invalid entry %q: %q", destination, appID)
		}
	}
	for appID, digest := range spec.SHA256 {
		if len(digest) != 64 {
			return Spec{}, fmt.Errorf("live bootfs spec: invalid sha256 for %s", appID)
		}
		if _, err := hex.DecodeString(digest); err != nil {
			return Spec{}, fmt.Errorf("live bootfs spec: invalid sha256 for %s: %w", appID, err)
		}
	}
	return spec, nil
}

func Build(workspace *config.Workspace, opts Options) (Result, error) {
	if workspace == nil {
		return Result{}, fmt.Errorf("live bootfs: nil workspace")
	}
	spec, err := LoadSpec(workspace.Path(SpecPath))
	if err != nil {
		return Result{}, err
	}
	selected := make(map[string]config.App)
	paths := make([]string, 0, len(spec.Files))
	for destination, appID := range spec.Files {
		app, ok := workspace.App(appID)
		if !ok || app.Kind() != "file" {
			return Result{}, fmt.Errorf("live bootfs: unknown file app %q for %s", appID, destination)
		}
		selected[appID] = app
		paths = append(paths, destination)
	}
	sort.Strings(paths)
	for appID := range spec.SHA256 {
		if _, ok := selected[appID]; !ok {
			return Result{}, fmt.Errorf("live bootfs: checksum for unselected app %s", appID)
		}
	}
	if !opts.NoBuild {
		// Build only this profile's apps. Never run the normal rootfs/ESP sync.
		profile := *workspace
		profile.AppsMap = make(map[string]config.App, len(selected)+1)
		for id, app := range selected {
			profile.AppsMap[id] = app
		}
		initApp, ok := workspace.App("seed0boot")
		if !ok {
			return Result{}, fmt.Errorf("live bootfs: missing seed0boot app")
		}
		profile.AppsMap["seed0boot"] = initApp
		profile.Skip = config.Skip{}
		if _, err := buildsys.BuildUserland(&profile, buildsys.UserlandOptions{}); err != nil {
			return Result{}, err
		}
	}
	initApp, ok := workspace.App("seed0boot")
	if !ok {
		return Result{}, fmt.Errorf("live bootfs: missing seed0boot app")
	}
	initBytes, initLoadBytes, err := bootInitScratchUse(workspace.ArtifactPath(initApp))
	if err != nil {
		return Result{}, err
	}
	if !fitsBootScratch(initBytes, initLoadBytes, 0) {
		return Result{}, fmt.Errorf("live bootfs: seed0boot alone exceeds %d-byte boot scratch", bootScratchBytes)
	}

	outputDir := workspace.Path(OutputDir)
	manifestPath := filepath.Join(outputDir, ManifestName)
	imagePath := filepath.Join(outputDir, ImageName)
	var manifest strings.Builder
	manifest.WriteString("# Generated by pacgo live-bootfs. DO NOT EDIT.\n")
	var upperBound int64 = 104 + int64(len(paths))*56
	available := make(map[string]bool, len(paths))
	countedArtifact := make(map[string]bool, len(paths))
	checkedDigest := make(map[string]bool, len(spec.SHA256))
	for _, destination := range paths {
		app := selected[spec.Files[destination]]
		artifact := workspace.ArtifactPath(app)
		info, err := os.Lstat(artifact)
		if err != nil {
			return Result{}, fmt.Errorf("live bootfs: missing %s (%s): %w", destination, app.ID, err)
		}
		if !info.Mode().IsRegular() || info.Size() == 0 {
			return Result{}, fmt.Errorf("live bootfs: %s must be a nonempty regular file", artifact)
		}
		if expected := spec.SHA256[app.ID]; expected != "" && !checkedDigest[app.ID] {
			data, err := os.ReadFile(artifact)
			if err != nil {
				return Result{}, err
			}
			actual := fmt.Sprintf("%x", sha256.Sum256(data))
			if actual != expected {
				return Result{}, fmt.Errorf("live bootfs: %s checksum mismatch: got %s, want %s", app.ID, actual, expected)
			}
			checkedDigest[app.ID] = true
		}
		upperBound += int64(len(destination)) + 8
		if !countedArtifact[artifact] {
			upperBound += info.Size()
			countedArtifact[artifact] = true
		}
		available[destination] = true
		rel, err := filepath.Rel(outputDir, artifact)
		if err != nil {
			return Result{}, err
		}
		fmt.Fprintf(&manifest, "%s=%s\n", destination, filepath.ToSlash(rel))
	}
	if opts.AuthorizedKeysPath != "" {
		keyPath, err := filepath.Abs(opts.AuthorizedKeysPath)
		if err != nil {
			return Result{}, err
		}
		key, err := os.ReadFile(keyPath)
		if err != nil {
			return Result{}, fmt.Errorf("live bootfs: SSH public key: %w", err)
		}
		if err := validateAuthorizedKey(key); err != nil {
			return Result{}, fmt.Errorf("live bootfs: SSH public key: %w", err)
		}
		const destination = "/root/.ssh/authorized_keys"
		rel, err := filepath.Rel(outputDir, keyPath)
		if err != nil {
			return Result{}, err
		}
		fmt.Fprintf(&manifest, "%s=%s\n", destination, filepath.ToSlash(rel))
		upperBound += int64(len(destination) + len(key) + 64)
	}
	if upperBound >= maxLiveRootBytes {
		return Result{}, fmt.Errorf("live bootfs: estimated RAM root %d bytes exceeds 64 MiB limit", upperBound)
	}
	if err := validateELFClosure(workspace, spec, paths, available); err != nil {
		return Result{}, err
	}
	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return Result{}, err
	}
	if err := writeIfChanged(manifestPath, []byte(manifest.String())); err != nil {
		return Result{}, err
	}
	rootImagePath := filepath.Join(outputDir, "ROOTFS.IMG")
	image, err := bootfs.BuildImage(manifestPath, rootImagePath)
	if err != nil {
		return Result{}, err
	}
	if image.Bytes >= maxLiveRootBytes {
		return Result{}, fmt.Errorf("live bootfs: RAM root archive %d bytes exceeds 64 MiB limit", image.Bytes)
	}
	if fitsBootScratch(initBytes, initLoadBytes, int64(image.Bytes)) {
		data, err := os.ReadFile(rootImagePath)
		if err != nil {
			return Result{}, err
		}
		if err := writeIfChanged(imagePath, data); err != nil {
			return Result{}, err
		}
		return Result{Manifest: manifestPath, Image: imagePath, Entries: image.Entries, Bytes: int64(image.Bytes)}, nil
	}
	// The boot scratch stages only the outer archive. filed expands this
	// immutable inner archive into its RAM root after boot.
	filedID := spec.Files["/sbin/filed.elf"]
	profileID := spec.Files["/etc/pacha/boot-profile"]
	rootID := spec.Files["/sbin/seed0root.elf"]
	if filedID == "" || profileID == "" || rootID == "" {
		return Result{}, fmt.Errorf("live bootfs: large archive needs filed, seed0root and boot profile in the outer archive")
	}
	data, err := os.ReadFile(rootImagePath)
	if err != nil {
		return Result{}, err
	}
	var compressed bytes.Buffer
	var length [8]byte
	binary.LittleEndian.PutUint64(length[:], uint64(len(data)))
	compressed.WriteString(packedRootMagic)
	compressed.Write(length[:])
	writer, err := zlib.NewWriterLevel(&compressed, zlib.BestCompression)
	if err != nil {
		return Result{}, err
	}
	if _, err := writer.Write(data); err != nil {
		return Result{}, err
	}
	if err := writer.Close(); err != nil {
		return Result{}, err
	}
	compressedPath := filepath.Join(outputDir, "ROOTFS.Z")
	if err := writeIfChanged(compressedPath, compressed.Bytes()); err != nil {
		return Result{}, err
	}
	outerManifestPath := filepath.Join(outputDir, "limine-bootfs.generated.txt")
	var outer strings.Builder
	outer.WriteString("# Generated by pacgo live-bootfs. DO NOT EDIT.\n")
	for _, item := range []struct{ destination, source string }{
		{"/etc/pacha/boot-profile", workspace.ArtifactPath(selected[profileID])},
		{"/sbin/filed.elf", workspace.ArtifactPath(selected[filedID])},
		{"/sbin/seed0root.elf", workspace.ArtifactPath(selected[rootID])},
		{"/srv/live-rootfs.z", compressedPath},
	} {
		rel, err := filepath.Rel(outputDir, item.source)
		if err != nil {
			return Result{}, err
		}
		fmt.Fprintf(&outer, "%s=%s\n", item.destination, filepath.ToSlash(rel))
	}
	if err := writeIfChanged(outerManifestPath, []byte(outer.String())); err != nil {
		return Result{}, err
	}
	outerImage, err := bootfs.BuildImage(outerManifestPath, imagePath)
	if err != nil {
		return Result{}, err
	}
	if !fitsBootScratch(initBytes, initLoadBytes, int64(outerImage.Bytes)) {
		return Result{}, fmt.Errorf("live bootfs: compressed outer archive %d bytes plus init %d bytes exceeds %d-byte boot scratch", outerImage.Bytes, initBytes, bootScratchBytes)
	}
	return Result{Manifest: outerManifestPath, Image: imagePath, Entries: image.Entries, Bytes: int64(outerImage.Bytes)}, nil
}

func validateAuthorizedKey(data []byte) error {
	if len(data) == 0 || len(data) > 4096 {
		return fmt.Errorf("expected one Ed25519 public key (at most 4096 bytes)")
	}
	line := strings.TrimSuffix(string(data), "\n")
	if strings.ContainsAny(line, "\r\n") {
		return fmt.Errorf("expected exactly one public-key line")
	}
	fields := strings.Fields(line)
	if len(fields) < 2 || fields[0] != "ssh-ed25519" {
		return fmt.Errorf("expected an ssh-ed25519 public key without options")
	}
	decoded, err := base64.StdEncoding.DecodeString(fields[1])
	if err != nil || len(decoded) != 51 ||
		binary.BigEndian.Uint32(decoded[:4]) != 11 ||
		string(decoded[4:15]) != "ssh-ed25519" ||
		binary.BigEndian.Uint32(decoded[15:19]) != 32 {
		return fmt.Errorf("invalid Ed25519 public-key payload")
	}
	return nil
}

func bootInitScratchUse(filename string) (imageBytes, loadBytes int64, err error) {
	info, err := os.Stat(filename)
	if err != nil {
		return 0, 0, fmt.Errorf("live bootfs: seed0boot image: %w", err)
	}
	if !info.Mode().IsRegular() || info.Size() <= 0 {
		return 0, 0, fmt.Errorf("live bootfs: seed0boot image must be a nonempty regular file")
	}
	image, err := elf.Open(filename)
	if err != nil {
		return 0, 0, fmt.Errorf("live bootfs: seed0boot ELF: %w", err)
	}
	defer image.Close()
	var maxEnd uint64
	for _, program := range image.Progs {
		if program.Type != elf.PT_LOAD || program.Memsz == 0 {
			continue
		}
		if program.Vaddr >= bootScratchBytes || program.Memsz > bootScratchBytes-program.Vaddr {
			return 0, 0, fmt.Errorf("live bootfs: seed0boot ELF load window exceeds %d-byte boot scratch", bootScratchBytes)
		}
		end := program.Vaddr + program.Memsz
		if end > maxEnd {
			maxEnd = end
		}
	}
	if maxEnd == 0 {
		return 0, 0, fmt.Errorf("live bootfs: seed0boot ELF has no loadable segments")
	}
	return info.Size(), int64((maxEnd + 4095) &^ 4095), nil
}

func fitsBootScratch(initBytes, initLoadBytes, archiveBytes int64) bool {
	if initBytes <= 0 || initLoadBytes <= 0 || archiveBytes < 0 ||
		initBytes > bootScratchBytes || initLoadBytes > bootScratchBytes || archiveBytes > bootScratchBytes {
		return false
	}
	align8 := func(n int64) int64 { return (n + 7) &^ 7 }
	// Bootfs is freed before the init ELF load window is allocated, but the
	// original init image remains in scratch throughout both stages.
	return align8(initBytes)+align8(archiveBytes) <= bootScratchBytes &&
		align8(initBytes)+align8(initLoadBytes) <= bootScratchBytes
}

func validateELFClosure(workspace *config.Workspace, spec Spec, paths []string, available map[string]bool) error {
	for _, destination := range paths {
		app, _ := workspace.App(spec.Files[destination])
		filename := workspace.ArtifactPath(app)
		file, err := os.Open(filename)
		if err != nil {
			return err
		}
		var magic [4]byte
		_, readErr := io.ReadFull(file, magic[:])
		_ = file.Close()
		if readErr != nil || magic != [4]byte{0x7f, 'E', 'L', 'F'} {
			continue
		}
		image, err := elf.Open(filename)
		if err != nil {
			return fmt.Errorf("live bootfs: parse %s: %w", destination, err)
		}
		interpreter := ""
		for _, segment := range image.Progs {
			if segment.Type != elf.PT_INTERP {
				continue
			}
			data, err := io.ReadAll(segment.Open())
			if err != nil {
				_ = image.Close()
				return fmt.Errorf("live bootfs: read interpreter of %s: %w", destination, err)
			}
			interpreter = strings.TrimRight(string(data), "\x00")
		}
		needed, err := image.ImportedLibraries()
		_ = image.Close()
		if err != nil {
			return fmt.Errorf("live bootfs: read dependencies of %s: %w", destination, err)
		}
		if err := requireELFDependencies(destination, interpreter, needed, available); err != nil {
			return err
		}
	}
	return nil
}

func requireELFDependencies(destination, interpreter string, needed []string, available map[string]bool) error {
	if interpreter != "" && !available[interpreter] {
		return fmt.Errorf("live bootfs: %s needs missing interpreter %s", destination, interpreter)
	}
	for _, library := range needed {
		if !available["/lib/"+library] && !available["/lib/linux/"+library] {
			return fmt.Errorf("live bootfs: %s needs missing library %s", destination, library)
		}
	}
	return nil
}

func writeIfChanged(filename string, data []byte) error {
	if old, err := os.ReadFile(filename); err == nil && bytes.Equal(old, data) {
		return nil
	}
	temp, err := os.CreateTemp(filepath.Dir(filename), ".live-bootfs-manifest-*")
	if err != nil {
		return err
	}
	defer os.Remove(temp.Name())
	if _, err := temp.Write(data); err != nil {
		_ = temp.Close()
		return err
	}
	if err := temp.Close(); err != nil {
		return err
	}
	return os.Rename(temp.Name(), filename)
}
