#ifndef PACHAOS_ABI_H
#define PACHAOS_ABI_H

#include <stdint.h>

enum {
    PACHAOS_SYSCALL_LOG = 1,

    PACHAOS_SYSCALL_PROCESS_CREATE = 2,
    PACHAOS_SYSCALL_PROCESS_KILL = 3,
    PACHAOS_SYSCALL_PROCESS_WAIT = 4,
    PACHAOS_SYSCALL_PROCESS_EXIT = 5,
    PACHAOS_SYSCALL_THREAD_CREATE = 6,
    PACHAOS_SYSCALL_THREAD_START = 7,
    PACHAOS_SYSCALL_THREAD_KILL = 8,
    PACHAOS_SYSCALL_THREAD_WAIT = 9,
    PACHAOS_SYSCALL_THREAD_EXIT = 10,
    PACHAOS_SYSCALL_PROCESS_SIGNAL = 11,
    PACHAOS_SYSCALL_PROCESS_SIGNAL_CTL = 12,
    PACHAOS_SYSCALL_PROCESS_STOP = 13,
    PACHAOS_SYSCALL_PROCESS_CONTINUE = 14,
    PACHAOS_SYSCALL_THREAD_SET_FS_BASE = 15,
    PACHAOS_SYSCALL_THREAD_SET_GS_BASE = 16,
    PACHAOS_SYSCALL_PROCESS_CLONE = 17,
    PACHAOS_SYSCALL_PROCESS_MAP = 18,
    PACHAOS_SYSCALL_PROCESS_MAP_BATCH = 19,
    PACHAOS_SYSCALL_PROCESS_EXEC_FROM = 20,
    PACHAOS_SYSCALL_PROCESS_MEMORY_BARRIER = 21,

    PACHAOS_SYSCALL_GETPID = 22,
    PACHAOS_SYSCALL_GETTID = 23,
    PACHAOS_SYSCALL_CLOCK_GETTIME = 24,
    PACHAOS_SYSCALL_NANOSLEEP = 25,
    PACHAOS_SYSCALL_FUTEX_WAIT = 26,
    PACHAOS_SYSCALL_FUTEX_WAKE = 27,
    PACHAOS_SYSCALL_GETRANDOM = 28,

    PACHAOS_SYSCALL_FD_CLOSE = 29,
    PACHAOS_SYSCALL_FD_DUP = 30,
    PACHAOS_SYSCALL_FD_GET_INFO = 31,
    PACHAOS_SYSCALL_FD_SET_FLAGS = 32,
    PACHAOS_SYSCALL_FD_READ = 33,
    PACHAOS_SYSCALL_FD_WRITE = 34,
    PACHAOS_SYSCALL_FD_READV = 35,
    PACHAOS_SYSCALL_FD_WRITEV = 36,
    PACHAOS_SYSCALL_FD_FCNTL = 37,
    PACHAOS_SYSCALL_FD_POLL = 38,
    PACHAOS_SYSCALL_FD_WAIT_MANY = 39,
    PACHAOS_SYSCALL_FD_IOCTL = 40,
    PACHAOS_SYSCALL_FD_STAT = 41,
    PACHAOS_SYSCALL_EVENTFD_CREATE = 42,
    PACHAOS_SYSCALL_PIPE_CREATE = 43,
    PACHAOS_SYSCALL_TIMERFD_CREATE = 44,
    PACHAOS_SYSCALL_TIMERFD_SETTIME = 45,
    PACHAOS_SYSCALL_TIMERFD_GETTIME = 46,
    PACHAOS_SYSCALL_VMO_CREATE = 47,
    PACHAOS_SYSCALL_VMO_REVOKE = 48,
    PACHAOS_SYSCALL_MMAP = 49,
    PACHAOS_SYSCALL_MUNMAP = 50,
    PACHAOS_SYSCALL_MPROTECT = 51,
    PACHAOS_SYSCALL_MREMAP = 52,
    PACHAOS_SYSCALL_MADVISE = 53,

    PACHAOS_SYSCALL_IPC_ENDPOINT_CREATE = 54,
    PACHAOS_SYSCALL_IPC_CHANNEL_CREATE = 55,
    PACHAOS_SYSCALL_IPC_SEND = 56,
    PACHAOS_SYSCALL_IPC_RECV = 57,
    PACHAOS_SYSCALL_IPC_CALL = 58,
    PACHAOS_SYSCALL_IPC_REPLY = 59,
    PACHAOS_SYSCALL_IPC_RECV_WAIT = 60,
};

#define PACHAOS_PROCESS_CLONE_CURRENT_THREAD (1ull << 0)
#define PACHAOS_PROCESS_CLONE_USER_FRAME (1ull << 1)
#define PACHAOS_PROCESS_SELF_FD UINT32_MAX
#define PACHAOS_THREAD_EXIT_CLEAR_TID (1ull << 0)
#define PACHAOS_PROCESS_MEMORY_BARRIER_FLAG_NONE 0ull
#define PACHAOS_PROCESS_MEMORY_BARRIER_KNOWN_FLAGS_MASK PACHAOS_PROCESS_MEMORY_BARRIER_FLAG_NONE

#define PACHAOS_PROCESS_SIGNAL_CTL_REGISTER 1ull
#define PACHAOS_PROCESS_SIGNAL_CTL_SET_MASK 2ull
#define PACHAOS_PROCESS_SIGNAL_CTL_RETURN 3ull
#define PACHAOS_PROCESS_SIGNAL_CTL_DELIVER_PENDING_FRAME 4ull
#define PACHAOS_PROCESS_SIGNAL_FRAME_MAGIC 0x5041434841534947ull
#define PACHAOS_PROCESS_SIGNAL_XSTATE_FEATURE_MASK 0x7ull
#define PACHAOS_PROCESS_SIGNAL_FRAME_SIZE 1024ull
#define PACHAOS_PROCESS_SIGNAL_RUNTIME_STACK_SIZE 4096ull

#define PACHAOS_PROCESS_MAP_ANYWHERE 0xffffffffffffffffull

enum {
    PACHAOS_SYSCALL_OK = 0,
    PACHAOS_SYSCALL_ERR_INVALID = 1,
    PACHAOS_SYSCALL_ERR_NOT_READY = 2,
    PACHAOS_SYSCALL_ERR_ALLOC = 3,
    PACHAOS_SYSCALL_ERR_MAP = 4,
    PACHAOS_SYSCALL_ERR_EMPTY = 5,
    PACHAOS_SYSCALL_ERR_CLOSED = 6,
};

enum {
    PACHAOS_PROT_READ = 1ull << 0,
    PACHAOS_PROT_WRITE = 1ull << 1,
    PACHAOS_PROT_EXEC = 1ull << 2,

    PACHAOS_MMAP_FIXED = 1ull << 0,
    PACHAOS_MMAP_FIXED_NOREPLACE = 1ull << 1,
    PACHAOS_MMAP_PRIVATE = 1ull << 2,
    PACHAOS_MMAP_SHARED = 1ull << 3,
    PACHAOS_MMAP_ANONYMOUS = 1ull << 4,
    PACHAOS_MMAP_NORESERVE = 1ull << 5,
};

enum {
    PACHAOS_CLOCK_REALTIME = 0,
    PACHAOS_CLOCK_MONOTONIC = 1,
};

struct pachaos_timespec {
    uint64_t tv_sec;
    uint64_t tv_nsec;
};

#endif
