#ifndef PACHAOS_ABI_H
#define PACHAOS_ABI_H

#include <stdint.h>

enum {
    PACHAOS_SYSCALL_LOG = 1,

    PACHAOS_SYSCALL_PROCESS_CREATE = 2,
    PACHAOS_SYSCALL_PROCESS_KILL = 3,
    PACHAOS_SYSCALL_PROCESS_WAIT = 4,
    PACHAOS_SYSCALL_PROCESS_EXIT = 5,
    PACHAOS_SYSCALL_THREAD_CREATE = 6,
    PACHAOS_SYSCALL_THREAD_START = 7,
    PACHAOS_SYSCALL_THREAD_KILL = 8,
    PACHAOS_SYSCALL_THREAD_WAIT = 9,
    PACHAOS_SYSCALL_THREAD_EXIT = 10,
    PACHAOS_SYSCALL_PROCESS_SIGNAL = 11,
    PACHAOS_SYSCALL_PROCESS_CONSUME_SIGNAL = 12,
    PACHAOS_SYSCALL_PROCESS_STOP = 13,
    PACHAOS_SYSCALL_PROCESS_CONTINUE = 14,
    PACHAOS_SYSCALL_THREAD_SET_FS_BASE = 15,
    PACHAOS_SYSCALL_THREAD_SET_GS_BASE = 16,
    PACHAOS_SYSCALL_PROCESS_CLONE = 17,
    PACHAOS_SYSCALL_PROCESS_MAP = 18,
    PACHAOS_SYSCALL_PROCESS_MAP_BATCH = 19,

    PACHAOS_SYSCALL_GETPID = 20,
    PACHAOS_SYSCALL_GETTID = 21,
    PACHAOS_SYSCALL_CLOCK_GETTIME = 22,
    PACHAOS_SYSCALL_NANOSLEEP = 23,
    PACHAOS_SYSCALL_FUTEX_WAIT = 24,
    PACHAOS_SYSCALL_FUTEX_WAKE = 25,
    PACHAOS_SYSCALL_GETRANDOM = 26,

    PACHAOS_SYSCALL_FD_CLOSE = 27,
    PACHAOS_SYSCALL_FD_DUP = 28,
    PACHAOS_SYSCALL_FD_GET_INFO = 29,
    PACHAOS_SYSCALL_FD_SET_FLAGS = 30,
    PACHAOS_SYSCALL_FD_READ = 31,
    PACHAOS_SYSCALL_FD_WRITE = 32,
    PACHAOS_SYSCALL_FD_READV = 33,
    PACHAOS_SYSCALL_FD_WRITEV = 34,
    PACHAOS_SYSCALL_FD_FCNTL = 35,
    PACHAOS_SYSCALL_FD_POLL = 36,
    PACHAOS_SYSCALL_FD_WAIT_MANY = 37,
    PACHAOS_SYSCALL_FD_IOCTL = 38,
    PACHAOS_SYSCALL_FD_STAT = 39,
    PACHAOS_SYSCALL_EVENTFD_CREATE = 40,
    PACHAOS_SYSCALL_TIMERFD_CREATE = 41,
    PACHAOS_SYSCALL_TIMERFD_SETTIME = 42,
    PACHAOS_SYSCALL_TIMERFD_GETTIME = 43,
    PACHAOS_SYSCALL_VMO_CREATE = 44,
    PACHAOS_SYSCALL_MMAP = 45,
    PACHAOS_SYSCALL_MUNMAP = 46,
    PACHAOS_SYSCALL_MPROTECT = 47,
    PACHAOS_SYSCALL_MREMAP = 48,
    PACHAOS_SYSCALL_MADVISE = 49,

    PACHAOS_SYSCALL_IPC_ENDPOINT_CREATE = 50,
    PACHAOS_SYSCALL_IPC_CHANNEL_CREATE = 51,
    PACHAOS_SYSCALL_IPC_SEND = 52,
    PACHAOS_SYSCALL_IPC_RECV = 53,
    PACHAOS_SYSCALL_IPC_CALL = 54,
    PACHAOS_SYSCALL_IPC_REPLY = 55,
    PACHAOS_SYSCALL_IPC_RECV_WAIT = 56,
};

#define PACHAOS_PROCESS_CLONE_CURRENT_THREAD (1ull << 0)
#define PACHAOS_PROCESS_CLONE_USER_FRAME (1ull << 1)

#define PACHAOS_PROCESS_MAP_ANYWHERE 0xffffffffffffffffull

enum {
    PACHAOS_SYSCALL_OK = 0,
    PACHAOS_SYSCALL_ERR_INVALID = 1,
    PACHAOS_SYSCALL_ERR_NOT_READY = 2,
    PACHAOS_SYSCALL_ERR_ALLOC = 3,
    PACHAOS_SYSCALL_ERR_MAP = 4,
    PACHAOS_SYSCALL_ERR_EMPTY = 5,
};

enum {
    PACHAOS_PROT_READ = 1ull << 0,
    PACHAOS_PROT_WRITE = 1ull << 1,
    PACHAOS_PROT_EXEC = 1ull << 2,

    PACHAOS_MMAP_FIXED = 1ull << 0,
    PACHAOS_MMAP_FIXED_NOREPLACE = 1ull << 1,
    PACHAOS_MMAP_PRIVATE = 1ull << 2,
    PACHAOS_MMAP_SHARED = 1ull << 3,
    PACHAOS_MMAP_ANONYMOUS = 1ull << 4,
    PACHAOS_MMAP_NORESERVE = 1ull << 5,
};

enum {
    PACHAOS_CLOCK_REALTIME = 0,
    PACHAOS_CLOCK_MONOTONIC = 1,
};

struct pachaos_timespec {
    uint64_t tv_sec;
    uint64_t tv_nsec;
};

#endif
