#ifndef PACHAOS_ABI_H
#define PACHAOS_ABI_H

#include <stdint.h>

enum {
    PACHAOS_SYSCALL_LOG = 1,

    PACHAOS_SYSCALL_PROCESS_CREATE = 2,
    PACHAOS_SYSCALL_PROCESS_KILL = 3,
    PACHAOS_SYSCALL_PROCESS_WAIT = 4,
    PACHAOS_SYSCALL_PROCESS_EXIT = 5,
    PACHAOS_SYSCALL_THREAD_CREATE = 6,
    PACHAOS_SYSCALL_THREAD_START = 7,
    PACHAOS_SYSCALL_THREAD_KILL = 8,
    PACHAOS_SYSCALL_THREAD_WAIT = 9,
    PACHAOS_SYSCALL_THREAD_EXIT = 10,
    PACHAOS_SYSCALL_THREAD_SET_FS_BASE = 11,
    PACHAOS_SYSCALL_THREAD_SET_GS_BASE = 12,
    PACHAOS_SYSCALL_PROCESS_CLONE = 13,
    PACHAOS_SYSCALL_PROCESS_MAP = 14,
    PACHAOS_SYSCALL_PROCESS_MAP_BATCH = 15,

    PACHAOS_SYSCALL_GETPID = 16,
    PACHAOS_SYSCALL_GETTID = 17,
    PACHAOS_SYSCALL_CLOCK_GETTIME = 18,
    PACHAOS_SYSCALL_NANOSLEEP = 19,
    PACHAOS_SYSCALL_FUTEX_WAIT = 20,
    PACHAOS_SYSCALL_FUTEX_WAKE = 21,
    PACHAOS_SYSCALL_GETRANDOM = 22,

    PACHAOS_SYSCALL_FD_CLOSE = 23,
    PACHAOS_SYSCALL_FD_DUP = 24,
    PACHAOS_SYSCALL_FD_GET_INFO = 25,
    PACHAOS_SYSCALL_FD_SET_FLAGS = 26,
    PACHAOS_SYSCALL_FD_READ = 27,
    PACHAOS_SYSCALL_FD_WRITE = 28,
    PACHAOS_SYSCALL_FD_READV = 29,
    PACHAOS_SYSCALL_FD_WRITEV = 30,
    PACHAOS_SYSCALL_FD_FCNTL = 31,
    PACHAOS_SYSCALL_FD_POLL = 32,
    PACHAOS_SYSCALL_FD_WAIT_MANY = 33,
    PACHAOS_SYSCALL_FD_IOCTL = 34,
    PACHAOS_SYSCALL_FD_STAT = 35,
    PACHAOS_SYSCALL_EVENTFD_CREATE = 36,
    PACHAOS_SYSCALL_TIMERFD_CREATE = 37,
    PACHAOS_SYSCALL_TIMERFD_SETTIME = 38,
    PACHAOS_SYSCALL_TIMERFD_GETTIME = 39,
    PACHAOS_SYSCALL_VMO_CREATE = 40,
    PACHAOS_SYSCALL_MMAP = 41,
    PACHAOS_SYSCALL_MUNMAP = 42,
    PACHAOS_SYSCALL_MPROTECT = 43,
    PACHAOS_SYSCALL_MREMAP = 44,
    PACHAOS_SYSCALL_MADVISE = 45,

    PACHAOS_SYSCALL_IPC_ENDPOINT_CREATE = 46,
    PACHAOS_SYSCALL_IPC_CHANNEL_CREATE = 47,
    PACHAOS_SYSCALL_IPC_SEND = 48,
    PACHAOS_SYSCALL_IPC_RECV = 49,
    PACHAOS_SYSCALL_IPC_CALL = 50,
    PACHAOS_SYSCALL_IPC_REPLY = 51,
    PACHAOS_SYSCALL_IPC_RECV_WAIT = 52,
};

#define PACHAOS_PROCESS_CLONE_CURRENT_THREAD (1ull << 0)
#define PACHAOS_PROCESS_CLONE_USER_FRAME (1ull << 1)

#define PACHAOS_PROCESS_MAP_ANYWHERE 0xffffffffffffffffull

enum {
    PACHAOS_SYSCALL_OK = 0,
    PACHAOS_SYSCALL_ERR_INVALID = 1,
    PACHAOS_SYSCALL_ERR_NOT_READY = 2,
    PACHAOS_SYSCALL_ERR_ALLOC = 3,
    PACHAOS_SYSCALL_ERR_MAP = 4,
    PACHAOS_SYSCALL_ERR_EMPTY = 5,
};

enum {
    PACHAOS_PROT_READ = 1ull << 0,
    PACHAOS_PROT_WRITE = 1ull << 1,
    PACHAOS_PROT_EXEC = 1ull << 2,

    PACHAOS_MMAP_FIXED = 1ull << 0,
    PACHAOS_MMAP_FIXED_NOREPLACE = 1ull << 1,
    PACHAOS_MMAP_PRIVATE = 1ull << 2,
    PACHAOS_MMAP_SHARED = 1ull << 3,
    PACHAOS_MMAP_ANONYMOUS = 1ull << 4,
    PACHAOS_MMAP_NORESERVE = 1ull << 5,
};

enum {
    PACHAOS_CLOCK_REALTIME = 0,
    PACHAOS_CLOCK_MONOTONIC = 1,
};

struct pachaos_timespec {
    uint64_t tv_sec;
    uint64_t tv_nsec;
};

#endif
