#pragma once

enum {
    FILED_RIGHT_LOOKUP = 1u << 0,
    FILED_RIGHT_READ = 1u << 1,
    FILED_RIGHT_WRITE = 1u << 2,
    FILED_RIGHT_EXEC = 1u << 3,
    FILED_RIGHT_STAT = 1u << 4,
    FILED_RIGHT_GETDENTS = 1u << 5,
    FILED_RIGHT_CREATE = 1u << 6,
    FILED_RIGHT_REMOVE = 1u << 7,
    FILED_RIGHT_RENAME = 1u << 8,

    FILED_OPEN_CREATE = 1u << 0,
    FILED_OPEN_EXCLUSIVE = 1u << 1,
    FILED_OPEN_TRUNCATE = 1u << 2,
    FILED_OPEN_DIRECTORY = 1u << 3,
    FILED_OPEN_NOFOLLOW = 1u << 4,
    FILED_OPEN_CLOEXEC = 1u << 5,
    FILED_OPEN_APPEND = 1u << 6,
    FILED_OPEN_NONBLOCK = 1u << 7,
    FILED_OPEN_SYNC = 1u << 8,

    FILED_FD_CLOEXEC = 1u << 0,

    FILED_FILE_APPEND = 1u << 0,
    FILED_FILE_NONBLOCK = 1u << 1,
    FILED_FILE_SYNC = 1u << 2,
};
