schema_version = 1

[app]
id = "libc_musl"
kind = "file"
role = "service"

[source.file]
path = ".artifacts/userland-fixtures/alpine-clang-root/lib/libc.musl-x86_64.so.1"
rebuild_tool = "wsl"
rebuild_dir = "."
rebuild_args = ["-e", "bash", "tools/build_wsl_alpine_clang.sh"]

[build]
format = "blob"
target = ""
optimize = "release"
output_name = "LIBC.SO"
strip = false

[[publish]]
id = "rootfs"
fs = "rootfs"
path = "/lib/libc.so"

[[publish]]
id = "rootfs-loader"
fs = "rootfs"
path = "/lib/ld-musl-x86_64.so.1"
