schema_version = 1

[app]
id = "capwm_smoke"
kind = "cargo"
role = "demo"

[source.cargo]
manifest = "user/rust/Cargo.toml"
package = "capwm_smoke"
bin = "capwm_smoke"
target = "x86_64-unknown-none"
target_dir = ".artifacts/cargo-target"

[build]
format = "pie-elf"
target = "x86_64-unknown-none"
optimize = "release"
output_name = "CAPWMSMK.ELF"
strip = true

[[publish]]
id = "rootfs"
fs = "rootfs"
path = "/cmd/capwm_smoke.elf"
