schema_version = 1

[app]
id = "hello_world"
kind = "cargo"
role = "demo"

[source.cargo]
manifest = "userland/programs/hello_world/Cargo.toml"
package = "hello_world"
bin = "hello_world"
target = "x86_64-unknown-none"
target_dir = ".artifacts/cargo-target"

[build]
format = "pie-elf"
target = "x86_64-unknown-none"
optimize = "release"
output_name = "HELLOWLD.ELF"
strip = true

[[publish]]
id = "rootfs"
fs = "rootfs"
path = "/cmd/hello_world.elf"
