[package]
name = "pachafetch"
version = "0.1.0"
edition = "2024"

[dependencies]
cap_std = { path = "../cap_std" }
caplibgl = { path = "../caplibgl" }
capwm_client = { path = "../capwm_client" }
pachaland_assets = { path = "../pachaland_assets" }
pitty_assets = { path = "../pitty_assets" }
rt_alloc = { path = "../rt_alloc" }
rt_core = { path = "../rt_core" }

[[bin]]
name = "pachafetch"
path = "src/main.rs"
