[package]
name = "capgl_shader_wave"
version = "0.1.0"
edition = "2024"

[dependencies]
cap_std = { path = "../cap_std" }
caplibgl = { path = "../caplibgl" }
capwm_client = { path = "../capwm_client" }
rt_alloc = { path = "../rt_alloc" }
rt_core = { path = "../rt_core" }

[[bin]]
name = "capgl_shader_wave"
path = "src/main.rs"
