const abi_root = @import("kernel_abi_root");
const kernel = @import("../kernel.zig");
const capability = @import("../capability.zig");
const pmm = @import("../memory/pmm.zig");
const scheduler = @import("../scheduler.zig");
const user_programs = @import("../user_programs.zig");
const x86_platform = @import("../arch/x86_64/platform.zig");
const boot_layout = @import("boot_layout.zig");

pub const four_gib = boot_layout.four_gib;
pub const page_entries = boot_layout.page_entries;
pub const user_va = boot_layout.user_va;
pub const user_elf_base_va = boot_layout.user_elf_base_va;
pub const user_stack_top = boot_layout.user_stack_top;
pub const user_stack_page_va = boot_layout.user_stack_page_va;
pub const user_entry_rsp = boot_layout.user_entry_rsp;
pub const user_program_max_load_bytes = boot_layout.user_program_max_load_bytes;
pub const boot_log_console_stack_page_va = boot_layout.boot_log_console_stack_page_va;
pub const boot_log_console_stack_top = boot_layout.boot_log_console_stack_top;
pub const boot_log_console_entry_rsp = boot_layout.boot_log_console_entry_rsp;
pub const boot_log_user_va = boot_layout.boot_log_user_va;
pub const framebuffer_window_bytes = boot_layout.framebuffer_window_bytes;
pub const phys_copy_window_va = boot_layout.phys_copy_window_va;

pub const iommu_no_cap_driver_mode: kernel.IommuNoCapDriverMode = .shadow;
pub const user_entry_rflags: u64 = 0x202;
pub const reserved_low_mem_end: u64 = 64 * 1024 * 1024;
pub const canonical_user_limit_exclusive: u64 = 0x0000_8000_0000_0000;

pub const user_unmapped_test_va: u64 = 0x20100000;
pub const user_dma_verify_va: u64 = 0x20110000;
pub const user_recovery_stop_va: u64 = 0x20200000;
pub const page_addr_mask: u64 = 0x000F_FFFF_FFFF_F000;
pub const physical_map_limit_exclusive: u64 = page_addr_mask + 0x1000;
pub const gdt_kernel_code_selector: u16 = x86_platform.gdt_kernel_code_selector;
pub const gdt_kernel_data_selector: u16 = x86_platform.gdt_kernel_data_selector;
pub const gdt_user_code_selector: u16 = x86_platform.gdt_user_code_selector;
pub const gdt_user_data_selector: u16 = x86_platform.gdt_user_data_selector;
pub const gdt_tss_selector: u16 = x86_platform.gdt_tss_selector;

pub const page_present: u64 = x86_platform.page_present;
pub const page_rw: u64 = x86_platform.page_rw;
pub const page_user: u64 = x86_platform.page_user;
pub const page_ps: u64 = x86_platform.page_ps;
pub const lapic_timer_vector: u8 = 0x40;
pub const lapic_timer_initial_count: u32 = 50_000;
pub const scheduler_quantum_ticks: u64 = 2;
pub const bootlog_auto_launch_min_visible_ticks: u64 = 1;
pub const scheduler_log_switch = false;
pub const scheduler_switch_log_max_lines: u64 = 96;
pub const scheduler_log_int80 = false;
pub const scheduler_int80_log_max_lines: u64 = 192;
pub const scheduler_race_log_max_lines: u64 = 128;
pub const enable_switch_thread_syscall_log = false;
pub const user_log_max_bytes: usize = 256;
pub const fx_state_bytes: usize = 512;
pub const debug_skip_syscall_fx_state = true;
pub const debug_skip_timer_fx_state = false;
pub const boot_log_max_bytes: usize = 32 * 1024;
pub const boot_log_page_header_bytes: usize = 8;
pub const boot_log_page_payload_bytes: usize = 4096 - boot_log_page_header_bytes;
pub const boot_log_status_offset: usize = 4;

pub const debug_skip_exit_boot_services = false;
pub const debug_skip_cr3_switch = false;
pub const debug_trigger_page_fault_test = false;
pub const user_process_count: usize = kernel.process_count;
pub const user_thread_count: usize = scheduler.max_thread_slots;
pub const UserAddressSpace = capability.UserAddressSpace;

pub const syscall_alloc_page: u64 = 0x1;
pub const syscall_map_page: u64 = 0x2;
pub const syscall_move_cap: u64 = 0x3;
pub const syscall_drop_present: u64 = 0x4;
pub const syscall_switch_thread: u64 = 0x5;
pub const syscall_send_cap: u64 = 0x6;
pub const syscall_revoke_tree: u64 = 0x7;
pub const syscall_grant_cap: u64 = 0x8;
pub const syscall_log: u64 = 0x9;
pub const syscall_recv_cap: u64 = 0xA;
pub const syscall_map_mmio: u64 = 0xB;
pub const syscall_alloc_map_pages: u64 = 0xC;
pub const syscall_queue_submit: u64 = 0xE;
pub const syscall_queue_notify: u64 = 0xF;
pub const syscall_untyped_alloc: u64 = 0x10;
pub const syscall_untyped_retype_pages: u64 = 0x11;
pub const syscall_untyped_reset: u64 = 0x12;
pub const syscall_untyped_alloc_map_pages: u64 = 0x13;
pub const syscall_grant_caps_batch: u64 = 0x14;
pub const syscall_map_pages_batch: u64 = 0x15;
pub const syscall_launch_pie_user: u64 = 0x16;
pub const syscall_wait_event: u64 = 0x17;
pub const syscall_batch_max_pages: usize = 64;

pub const user_program_cfg: user_programs.Config = .{
    .syscall_alloc_page = syscall_alloc_page,
    .syscall_map_page = syscall_map_page,
    .syscall_move_cap = syscall_move_cap,
    .syscall_drop_present = syscall_drop_present,
    .syscall_switch_thread = syscall_switch_thread,
    .syscall_send_cap = syscall_send_cap,
    .syscall_revoke_tree = syscall_revoke_tree,
    .syscall_grant_cap = syscall_grant_cap,
    .syscall_log = syscall_log,
    .user_unmapped_test_va = user_unmapped_test_va,
    .user_dma_verify_va = user_dma_verify_va,
    .user_recovery_stop_va = user_recovery_stop_va,
};

pub const syscall_ok: u64 = 0;
pub const syscall_err_invalid = 1;
pub const syscall_err_not_ready = 2;
pub const syscall_err_alloc = 4;
pub const syscall_err_map = 5;
pub const syscall_err_move = 6;
pub const syscall_err_drop_present = 7;
pub const syscall_err_send = 8;
pub const syscall_err_endpoint = 9;
pub const syscall_err_revoke = 10;
pub const syscall_err_grant = 11;
pub const syscall_err_log = 12;
pub const syscall_err_empty = 13;
pub const syscall_alloc_map_drop_cap_flag: u64 = 0x2;

pub const MemoryStats = pmm.MemoryStats;
