schema_version = 1

[app]
id = "shell"
kind = "zig"
role = "command"

[source.zig]
entry = "userland/programs/shell.zig"
module = "abi_root"

[build]
format = "pie-elf"
target = "x86_64-freestanding-none"
optimize = "ReleaseSmall"
output_name = "SHELL.ELF"
strip = true

[[publish]]
id = "bootfs"
fs = "bootfs"
path = "/cmd/shell.elf"

[[publish]]
id = "rootfs"
fs = "rootfs"
path = "/cmd/shell.elf"

