[package]
name = "rust_gl_query_demo"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "rust_gl_query_demo"
path = "src/main.rs"

[dependencies]
caplibgl = { path = "../../../user/rust/caplibgl" }
rt_alloc = { path = "../../../user/rust/rt_alloc" }
rt_core = { path = "../../../user/rust/rt_core" }
