// Generated by tools/logo_to_fb.py. Do not edit manually.
pub const source_png = "PachaOSLogo/logo.png";
pub const width: usize = 320;
pub const height: usize = 110;
pub const pixel_count: usize = width * height;
pub const pixel_bytes = @embedFile("generated_pacha_logo.bin");

pub fn packedPixel(index: usize) u32 {
    const offset = index * 4;
    return @as(u32, pixel_bytes[offset]) |
        (@as(u32, pixel_bytes[offset + 1]) << 8) |
        (@as(u32, pixel_bytes[offset + 2]) << 16) |
        (@as(u32, pixel_bytes[offset + 3]) << 24);
}
