#ifndef PACHA_LAUNCH_H
#define PACHA_LAUNCH_H

#include "pacha/ipc.h"

/* Userland launch roles. These are explicit policies, never defaults in
 * PROCESS_CREATE. Delegators add TRANSFER only to resources passed onward. */
#define PACHA_LAUNCH_LOG (PACHA_FD_RIGHT_INSPECT | PACHA_FD_RIGHT_CLOSE | \
    PACHA_FD_RIGHT_POLL | PACHA_FD_RIGHT_WRITE)
#define PACHA_LAUNCH_BLOB (PACHA_FD_RIGHT_INSPECT | PACHA_FD_RIGHT_CLOSE | \
    PACHA_FD_RIGHT_READ | PACHA_FD_RIGHT_MAP_READ)
#define PACHA_LAUNCH_SERVER (PACHA_FD_RIGHT_INSPECT | PACHA_FD_RIGHT_CLOSE | \
    PACHA_FD_RIGHT_RECV | PACHA_FD_RIGHT_WAIT | PACHA_FD_RIGHT_POLL)
#define PACHA_LAUNCH_CLIENT (PACHA_FD_RIGHT_INSPECT | PACHA_FD_RIGHT_CLOSE | \
    PACHA_FD_RIGHT_CALL | PACHA_FD_RIGHT_WAIT | PACHA_FD_RIGHT_POLL)
#define PACHA_LAUNCH_SIGNAL (PACHA_FD_RIGHT_INSPECT | PACHA_FD_RIGHT_CLOSE | \
    PACHA_FD_RIGHT_SEND | PACHA_FD_RIGHT_WAIT | PACHA_FD_RIGHT_POLL)
#define PACHA_LAUNCH_DEVICE_DRIVER (PACHA_FD_RIGHT_INSPECT | PACHA_FD_RIGHT_CLOSE | \
    PACHA_FD_RIGHT_QUERY | PACHA_FD_RIGHT_CONFIG_READ | PACHA_FD_RIGHT_CONFIG_WRITE | \
    PACHA_FD_RIGHT_DERIVE_MMIO | PACHA_FD_RIGHT_DERIVE_DMA | PACHA_FD_RIGHT_DERIVE_IRQ | \
    PACHA_FD_RIGHT_MMIO_MAP_READ | PACHA_FD_RIGHT_MMIO_MAP_WRITE | \
    PACHA_FD_RIGHT_CPU_READ | PACHA_FD_RIGHT_CPU_WRITE | \
    PACHA_FD_RIGHT_DMA_READ | PACHA_FD_RIGHT_DMA_WRITE | \
    PACHA_FD_RIGHT_IRQ_WAIT | PACHA_FD_RIGHT_IRQ_ACK | PACHA_FD_RIGHT_BUS_MASTER)

#define PACHA_LAUNCH_GRANT(source, target, access) \
    { .source_fd = (uint64_t)(source), .target_fd = (uint64_t)(target), \
      .rights = (access), .flags = 0 }
#define PACHA_LAUNCH_LOG_GRANTS(extra) \
    PACHA_LAUNCH_GRANT(1, 1, PACHA_LAUNCH_LOG | (extra)), \
    PACHA_LAUNCH_GRANT(2, 2, PACHA_LAUNCH_LOG | (extra))

#endif
