#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

enum pacha_linux_errno {
    PACHA_LINUX_EPERM = 1,
    PACHA_LINUX_ENOENT = 2,
    PACHA_LINUX_ESRCH = 3,
    PACHA_LINUX_EINTR = 4,
    PACHA_LINUX_EIO = 5,
    PACHA_LINUX_ENXIO = 6,
    PACHA_LINUX_E2BIG = 7,
    PACHA_LINUX_ENOEXEC = 8,
    PACHA_LINUX_EBADF = 9,
    PACHA_LINUX_ECHILD = 10,
    PACHA_LINUX_EAGAIN = 11,
    PACHA_LINUX_ENOMEM = 12,
    PACHA_LINUX_EACCES = 13,
    PACHA_LINUX_EFAULT = 14,
    PACHA_LINUX_EEXIST = 17,
    PACHA_LINUX_EXDEV = 18,
    PACHA_LINUX_ENODEV = 19,
    PACHA_LINUX_ENOTDIR = 20,
    PACHA_LINUX_EISDIR = 21,
    PACHA_LINUX_EINVAL = 22,
    PACHA_LINUX_EMFILE = 24,
    PACHA_LINUX_ENOTTY = 25,
    PACHA_LINUX_ENOSPC = 28,
    PACHA_LINUX_ESPIPE = 29,
    PACHA_LINUX_EPIPE = 32,
    PACHA_LINUX_ERANGE = 34,
    PACHA_LINUX_ENAMETOOLONG = 36,
    PACHA_LINUX_ENOSYS = 38,
    PACHA_LINUX_ENOTEMPTY = 39,
    PACHA_LINUX_ELOOP = 40,
    PACHA_LINUX_EOVERFLOW = 75,
    PACHA_LINUX_EPROTONOSUPPORT = 93,
    PACHA_LINUX_ESOCKTNOSUPPORT = 94,
    PACHA_LINUX_ENOTSUP = 95,
    PACHA_LINUX_EOPNOTSUPP = 95,
    PACHA_LINUX_EAFNOSUPPORT = 97,
    PACHA_LINUX_ENETDOWN = 100,
    PACHA_LINUX_ENETUNREACH = 101,
    PACHA_LINUX_EISCONN = 106,
    PACHA_LINUX_ENOTCONN = 107,
    PACHA_LINUX_ETIMEDOUT = 110,
    PACHA_LINUX_ECONNREFUSED = 111,
    PACHA_LINUX_EALREADY = 114,
    PACHA_LINUX_EINPROGRESS = 115,
};

enum pacha_status_value {
    PACHA_STATUS_OK = 0,
    PACHA_STATUS_EPERM = -PACHA_LINUX_EPERM,
    PACHA_STATUS_ENOENT = -PACHA_LINUX_ENOENT,
    PACHA_STATUS_ESRCH = -PACHA_LINUX_ESRCH,
    PACHA_STATUS_EIO = -PACHA_LINUX_EIO,
    PACHA_STATUS_ECHILD = -PACHA_LINUX_ECHILD,
    PACHA_STATUS_EAGAIN = -PACHA_LINUX_EAGAIN,
    PACHA_STATUS_ENOMEM = -PACHA_LINUX_ENOMEM,
    PACHA_STATUS_EACCES = -PACHA_LINUX_EACCES,
    PACHA_STATUS_EFAULT = -PACHA_LINUX_EFAULT,
    PACHA_STATUS_ENODEV = -PACHA_LINUX_ENODEV,
    PACHA_STATUS_EINVAL = -PACHA_LINUX_EINVAL,
    PACHA_STATUS_ENOTSUP = -PACHA_LINUX_ENOTSUP,
};

enum pacha_status_domain {
    PACHA_STATUS_DOMAIN_NONE = 0,
    PACHA_STATUS_DOMAIN_KERNEL = 1,
    PACHA_STATUS_DOMAIN_FILED = 2,
    PACHA_STATUS_DOMAIN_TERMD = 3,
    PACHA_STATUS_DOMAIN_LPRS = 4,
};

enum pacha_status_stage {
    PACHA_STATUS_STAGE_NONE = 0,
    PACHA_STATUS_STAGE_KERNEL_SYSCALL = 1,
    PACHA_STATUS_STAGE_MAP_PAGE = 2,
    PACHA_STATUS_STAGE_CHILD_RPC_CALL = 3,
    PACHA_STATUS_STAGE_CHILD_RPC_RECV = 4,
    PACHA_STATUS_STAGE_REPLY_MAGIC = 5,
    PACHA_STATUS_STAGE_CHILD_STATUS = 6,
    PACHA_STATUS_STAGE_STATUS_MAP = 7,
    PACHA_STATUS_STAGE_DISPATCH = 8,
    PACHA_STATUS_STAGE_VALIDATION = 9,
    PACHA_STATUS_STAGE_DIAGNOSTIC = 10,
};

int64_t pacha_kernel_status_to_errno(int64_t status);

#define LPR_LINUX_EPERM PACHA_LINUX_EPERM
#define LPR_LINUX_ENOENT PACHA_LINUX_ENOENT
#define LPR_LINUX_ESRCH PACHA_LINUX_ESRCH
#define LPR_LINUX_EINTR PACHA_LINUX_EINTR
#define LPR_LINUX_EIO PACHA_LINUX_EIO
#define LPR_LINUX_E2BIG PACHA_LINUX_E2BIG
#define LPR_LINUX_EBADF PACHA_LINUX_EBADF
#define LPR_LINUX_ECHILD PACHA_LINUX_ECHILD
#define LPR_LINUX_EAGAIN PACHA_LINUX_EAGAIN
#define LPR_LINUX_ENOMEM PACHA_LINUX_ENOMEM
#define LPR_LINUX_EACCES PACHA_LINUX_EACCES
#define LPR_LINUX_EFAULT PACHA_LINUX_EFAULT
#define LPR_LINUX_EEXIST PACHA_LINUX_EEXIST
#define LPR_LINUX_EXDEV PACHA_LINUX_EXDEV
#define LPR_LINUX_ENODEV PACHA_LINUX_ENODEV
#define LPR_LINUX_ENOTDIR PACHA_LINUX_ENOTDIR
#define LPR_LINUX_EISDIR PACHA_LINUX_EISDIR
#define LPR_LINUX_EINVAL PACHA_LINUX_EINVAL
#define LPR_LINUX_EMFILE PACHA_LINUX_EMFILE
#define LPR_LINUX_ENOTTY PACHA_LINUX_ENOTTY
#define LPR_LINUX_ENOSPC PACHA_LINUX_ENOSPC
#define LPR_LINUX_ESPIPE PACHA_LINUX_ESPIPE
#define LPR_LINUX_EPIPE PACHA_LINUX_EPIPE
#define LPR_LINUX_ENAMETOOLONG PACHA_LINUX_ENAMETOOLONG
#define LPR_LINUX_ERANGE PACHA_LINUX_ERANGE
#define LPR_LINUX_ENOTEMPTY PACHA_LINUX_ENOTEMPTY
#define LPR_LINUX_ELOOP PACHA_LINUX_ELOOP
#define LPR_LINUX_ENOSYS PACHA_LINUX_ENOSYS
#define LPR_LINUX_EOVERFLOW PACHA_LINUX_EOVERFLOW
#define LPR_LINUX_EPROTONOSUPPORT PACHA_LINUX_EPROTONOSUPPORT
#define LPR_LINUX_ESOCKTNOSUPPORT PACHA_LINUX_ESOCKTNOSUPPORT
#define LPR_LINUX_ENOTSUP PACHA_LINUX_ENOTSUP
#define LPR_LINUX_EOPNOTSUPP PACHA_LINUX_EOPNOTSUPP
#define LPR_LINUX_EAFNOSUPPORT PACHA_LINUX_EAFNOSUPPORT
#define LPR_LINUX_ENETDOWN PACHA_LINUX_ENETDOWN
#define LPR_LINUX_ENETUNREACH PACHA_LINUX_ENETUNREACH
#define LPR_LINUX_EISCONN PACHA_LINUX_EISCONN
#define LPR_LINUX_ENOTCONN PACHA_LINUX_ENOTCONN
#define LPR_LINUX_ETIMEDOUT PACHA_LINUX_ETIMEDOUT
#define LPR_LINUX_ECONNREFUSED PACHA_LINUX_ECONNREFUSED
#define LPR_LINUX_EALREADY PACHA_LINUX_EALREADY
#define LPR_LINUX_EINPROGRESS PACHA_LINUX_EINPROGRESS

#ifdef __cplusplus
}
#endif
