schema_version = 1

[app]
id = "alpine_key_61666e3f"
kind = "file"
role = "asset"

[source.file]
path = "userland/fixtures/alpine-keys/alpine-devel@lists.alpinelinux.org-61666e3f.rsa.pub"
rebuild_tool = "wsl"
rebuild_dir = "."
rebuild_args = ["-e", "bash", "tools/build_wsl_alpine_keys.sh"]

[build]
format = "blob"
target = ""
optimize = "release"
output_name = "ALPKEY66.PUB"
strip = false

[[publish]]
id = "rootfs_apk_key"
fs = "rootfs"
path = "/etc/apk/keys/alpine-devel@lists.alpinelinux.org-61666e3f.rsa.pub"
