schema_version = 1

[app]
id = "capgl_shader_wave"
kind = "cargo"
role = "demo"

[source.cargo]
manifest = "user/rust/Cargo.toml"
package = "capgl_shader_wave"
bin = "capgl_shader_wave"
target = "x86_64-unknown-none"
target_dir = ".artifacts/cargo-target"

[build]
format = "pie-elf"
target = "x86_64-unknown-none"
optimize = "release"
output_name = "CGLWAVE.ELF"
strip = true

[[publish]]
id = "rootfs"
fs = "rootfs"
path = "/cmd/capgl_shader_wave.elf"
