schema_version = 1

[app]
id = "virtio_blk"
kind = "zig"
role = "service"

[source.zig]
entry = "userland/programs/virtio_blk.zig"
module = "abi_root"

[build]
format = "pie-elf"
target = "x86_64-freestanding-none"
optimize = "ReleaseSmall"
output_name = "VBLKDRV.ELF"
strip = true

[[publish]]
id = "bootfs"
fs = "bootfs"
path = "/srv/virtio_blk.elf"

[[publish]]
id = "rootfs"
fs = "rootfs"
path = "/srv/virtio_blk.elf"

[startup]
publish = "bootfs"
action = "block_driver"
name = "block"
label = "block_driver"
load = "bootfs"
block = ["virtio_blk"]
provides = ["block_service"]

