schema_version = 1

[app]
id = "mbedtls"
kind = "file"
role = "service"

[source.file]
path = "userland/fixtures/libmbedtls.so.21"
rebuild_tool = "wsl"
rebuild_dir = "."
rebuild_args = ["-e", "bash", "tools/build_wsl_mbedtls.sh"]

[build]
format = "blob"
target = ""
optimize = "release"
output_name = "LIBMBEDTLS.SO.21"
strip = false

[[publish]]
id = "rootfs-soname"
fs = "rootfs"
path = "/lib/libmbedtls.so.21"

[[publish]]
id = "rootfs-linker"
fs = "rootfs"
path = "/lib/libmbedtls.so"
