#ifndef PACHA_ABI_H
#define PACHA_ABI_H

#include <stdint.h>

#define PACHA_SYSCALL_OK 0
#define PACHA_SYSCALL_ERR_INVALID 1
#define PACHA_SYSCALL_ERR_NOT_READY 2
#define PACHA_SYSCALL_ERR_ALLOC 3
#define PACHA_SYSCALL_ERR_MAP 4
#define PACHA_SYSCALL_ERR_EMPTY 5

#define PACHA_ERR_INVALID (-PACHA_SYSCALL_ERR_INVALID)
#define PACHA_ERR_NOT_READY (-PACHA_SYSCALL_ERR_NOT_READY)
#define PACHA_ERR_ALLOC (-PACHA_SYSCALL_ERR_ALLOC)
#define PACHA_ERR_MAP (-PACHA_SYSCALL_ERR_MAP)
#define PACHA_ERR_EMPTY (-PACHA_SYSCALL_ERR_EMPTY)

#define PACHA_PROCESS_SYSCALL_CREATE 2
#define PACHA_PROCESS_SYSCALL_KILL 3
#define PACHA_PROCESS_SYSCALL_WAIT 4
#define PACHA_PROCESS_SYSCALL_EXIT 5
#define PACHA_THREAD_SYSCALL_CREATE 6
#define PACHA_THREAD_SYSCALL_START 7
#define PACHA_THREAD_SYSCALL_KILL 8
#define PACHA_THREAD_SYSCALL_WAIT 9
#define PACHA_THREAD_SYSCALL_EXIT 10
#define PACHA_THREAD_SYSCALL_SET_FS_BASE 11
#define PACHA_THREAD_SYSCALL_SET_GS_BASE 12
#define PACHA_PROCESS_SYSCALL_CLONE 13
#define PACHA_PROCESS_SYSCALL_MAP 14
#define PACHA_PROCESS_SYSCALL_MAP_BATCH 15

#define PACHA_PROCESS_CLONE_CURRENT_THREAD (1ull << 0)
#define PACHA_PROCESS_CLONE_USER_FRAME (1ull << 1)

#define PACHA_PROCESS_CLONE_USER_FRAME_SIZE (18ull * 8ull)
#define PACHA_PROCESS_CLONE_USER_FRAME_R15_OFFSET (0ull * 8ull)
#define PACHA_PROCESS_CLONE_USER_FRAME_R14_OFFSET (1ull * 8ull)
#define PACHA_PROCESS_CLONE_USER_FRAME_R13_OFFSET (2ull * 8ull)
#define PACHA_PROCESS_CLONE_USER_FRAME_R12_OFFSET (3ull * 8ull)
#define PACHA_PROCESS_CLONE_USER_FRAME_RBP_OFFSET (4ull * 8ull)
#define PACHA_PROCESS_CLONE_USER_FRAME_RBX_OFFSET (5ull * 8ull)
#define PACHA_PROCESS_CLONE_USER_FRAME_R11_OFFSET (6ull * 8ull)
#define PACHA_PROCESS_CLONE_USER_FRAME_R10_OFFSET (7ull * 8ull)
#define PACHA_PROCESS_CLONE_USER_FRAME_R9_OFFSET (8ull * 8ull)
#define PACHA_PROCESS_CLONE_USER_FRAME_R8_OFFSET (9ull * 8ull)
#define PACHA_PROCESS_CLONE_USER_FRAME_RDI_OFFSET (10ull * 8ull)
#define PACHA_PROCESS_CLONE_USER_FRAME_RSI_OFFSET (11ull * 8ull)
#define PACHA_PROCESS_CLONE_USER_FRAME_RDX_OFFSET (12ull * 8ull)
#define PACHA_PROCESS_CLONE_USER_FRAME_RCX_OFFSET (13ull * 8ull)
#define PACHA_PROCESS_CLONE_USER_FRAME_RAX_OFFSET (14ull * 8ull)
#define PACHA_PROCESS_CLONE_USER_FRAME_RIP_OFFSET (15ull * 8ull)
#define PACHA_PROCESS_CLONE_USER_FRAME_RSP_OFFSET (16ull * 8ull)
#define PACHA_PROCESS_CLONE_USER_FRAME_RFLAGS_OFFSET (17ull * 8ull)

#define PACHA_PROCESS_MAP_ANYWHERE 0xffffffffffffffffull
#define PACHA_PROCESS_MAP_PRIVATE (1ull << 0)
#define PACHA_PROCESS_MAP_SHARED (1ull << 1)
#define PACHA_PROCESS_MAP_BATCH_MAX_ENTRIES 32ull
#define PACHA_PROCESS_DEFAULT_STACK_SIZE 0x20000ull
#define PACHA_AT_BOOTSTRAP_FD 0x70000000ull

#define PACHA_RUNTIME_SYSCALL_GETPID 16
#define PACHA_RUNTIME_SYSCALL_GETTID 17
#define PACHA_RUNTIME_SYSCALL_CLOCK_GETTIME 18
#define PACHA_RUNTIME_SYSCALL_NANOSLEEP 19
#define PACHA_RUNTIME_SYSCALL_FUTEX_WAIT 20
#define PACHA_RUNTIME_SYSCALL_FUTEX_WAKE 21
#define PACHA_RUNTIME_SYSCALL_GETRANDOM 22
#define PACHA_FD_SYSCALL_CLOSE 23
#define PACHA_FD_SYSCALL_DUP 24
#define PACHA_FD_SYSCALL_GET_INFO 25
#define PACHA_FD_SYSCALL_SET_FLAGS 26
#define PACHA_FD_SYSCALL_READ 27
#define PACHA_FD_SYSCALL_WRITE 28
#define PACHA_FD_SYSCALL_READV 29
#define PACHA_FD_SYSCALL_WRITEV 30
#define PACHA_FD_SYSCALL_FCNTL 31
#define PACHA_FD_SYSCALL_POLL 32
#define PACHA_FD_SYSCALL_WAIT_MANY 33
#define PACHA_FD_SYSCALL_IOCTL 34
#define PACHA_FD_SYSCALL_STAT 35
#define PACHA_FD_SYSCALL_EVENTFD_CREATE 36
#define PACHA_FD_SYSCALL_TIMERFD_CREATE 37
#define PACHA_FD_SYSCALL_TIMERFD_SETTIME 38
#define PACHA_FD_SYSCALL_TIMERFD_GETTIME 39
#define PACHA_FD_SYSCALL_VMO_CREATE 40
#define PACHA_VM_SYSCALL_MMAP 41
#define PACHA_VM_SYSCALL_MUNMAP 42
#define PACHA_VM_SYSCALL_MPROTECT 43
#define PACHA_VM_SYSCALL_MREMAP 44
#define PACHA_VM_SYSCALL_MADVISE 45
#define PACHA_IPC_SYSCALL_ENDPOINT_CREATE 46
#define PACHA_IPC_SYSCALL_CHANNEL_CREATE 47
#define PACHA_IPC_SYSCALL_SEND 48
#define PACHA_IPC_SYSCALL_RECV 49
#define PACHA_IPC_SYSCALL_CALL 50
#define PACHA_IPC_SYSCALL_REPLY 51
#define PACHA_IPC_SYSCALL_RECV_WAIT 52
#define PACHA_CAPSULE_SYSCALL_QUERY 53
#define PACHA_CAPSULE_SYSCALL_DERIVE_MMIO 54
#define PACHA_CAPSULE_SYSCALL_DERIVE_DMA_BUFFER 55
#define PACHA_CAPSULE_SYSCALL_DERIVE_DMA_MAPPING 56
#define PACHA_CAPSULE_SYSCALL_DERIVE_DMA_MAPPING_FROM_BUFFER 57
#define PACHA_CAPSULE_SYSCALL_DERIVE_IRQ 58
#define PACHA_CAPSULE_SYSCALL_PCI_CONFIG_READ 59
#define PACHA_CAPSULE_SYSCALL_PCI_CONFIG_WRITE 60
#define PACHA_CAPSULE_SYSCALL_PCI_BAR_INFO 61
#define PACHA_CAPSULE_SYSCALL_IRQ_POLL 62

#define PACHA_FD_RIGHT_INSPECT (1ull << 0)
#define PACHA_FD_RIGHT_DUP (1ull << 1)
#define PACHA_FD_RIGHT_TRANSFER (1ull << 2)
#define PACHA_FD_RIGHT_WAIT (1ull << 3)
#define PACHA_FD_RIGHT_POLL (1ull << 4)
#define PACHA_FD_RIGHT_SET_FLAGS (1ull << 5)
#define PACHA_FD_RIGHT_CLOSE (1ull << 6)
#define PACHA_FD_RIGHT_SEND (1ull << 7)
#define PACHA_FD_RIGHT_RECV (1ull << 8)
#define PACHA_FD_RIGHT_CALL (1ull << 9)
#define PACHA_FD_RIGHT_ACCEPT (1ull << 10)
#define PACHA_FD_RIGHT_BIND (1ull << 11)
#define PACHA_FD_RIGHT_ENDPOINT_SIGNAL (1ull << 12)
#define PACHA_FD_RIGHT_MAP_READ (1ull << 13)
#define PACHA_FD_RIGHT_MAP_WRITE (1ull << 14)
#define PACHA_FD_RIGHT_MAP_EXEC (1ull << 15)
#define PACHA_FD_RIGHT_SPAWN (1ull << 20)
#define PACHA_FD_RIGHT_START (1ull << 21)
#define PACHA_FD_RIGHT_KILL (1ull << 22)
#define PACHA_FD_RIGHT_DEBUG (1ull << 23)
#define PACHA_FD_RIGHT_MAP_INTO (1ull << 24)
#define PACHA_FD_RIGHT_SET_CONTEXT (1ull << 25)
#define PACHA_FD_RIGHT_QUERY (1ull << 27)
#define PACHA_FD_RIGHT_CONFIG_READ (1ull << 28)
#define PACHA_FD_RIGHT_CONFIG_WRITE (1ull << 29)
#define PACHA_FD_RIGHT_DERIVE_MMIO (1ull << 30)
#define PACHA_FD_RIGHT_DERIVE_DMA (1ull << 31)
#define PACHA_FD_RIGHT_DERIVE_IRQ (1ull << 32)
#define PACHA_FD_RIGHT_MMIO_MAP_READ (1ull << 33)
#define PACHA_FD_RIGHT_MMIO_MAP_WRITE (1ull << 34)
#define PACHA_FD_RIGHT_CPU_READ (1ull << 35)
#define PACHA_FD_RIGHT_CPU_WRITE (1ull << 36)
#define PACHA_FD_RIGHT_DMA_READ (1ull << 37)
#define PACHA_FD_RIGHT_DMA_WRITE (1ull << 38)
#define PACHA_FD_RIGHT_IRQ_WAIT (1ull << 39)
#define PACHA_FD_RIGHT_IRQ_ACK (1ull << 40)
#define PACHA_FD_RIGHT_BUS_MASTER (1ull << 41)
#define PACHA_FD_RIGHT_READ (1ull << 42)
#define PACHA_FD_RIGHT_WRITE (1ull << 43)

#define PACHA_FD_KIND_PROCESS 1
#define PACHA_FD_KIND_THREAD 2
#define PACHA_FD_KIND_EVENT 3
#define PACHA_FD_KIND_VMO 4
#define PACHA_FD_KIND_ENDPOINT 5
#define PACHA_FD_KIND_CHANNEL 6
#define PACHA_FD_KIND_REPLY 7
#define PACHA_FD_KIND_TIMER 13
#define PACHA_FD_KIND_SCHEDCTL 15
#define PACHA_FD_KIND_SCHED_EVENT 16

#define PACHA_MMAP_PRIVATE (1ull << 2)
#define PACHA_MMAP_SHARED (1ull << 3)
#define PACHA_MMAP_ANONYMOUS (1ull << 4)
#define PACHA_MMAP_PKEY_SHIFT 8
#define PACHA_MMAP_PKEY_MASK (0xfull << PACHA_MMAP_PKEY_SHIFT)
#define PACHA_PROT_READ (1ull << 0)
#define PACHA_PROT_WRITE (1ull << 1)
#define PACHA_PROT_EXEC (1ull << 2)

#define PACHA_FD_FCNTL_GET_FLAGS 1
#define PACHA_FD_FCNTL_SET_FLAGS 2
#define PACHA_FD_FCNTL_DUP 3

#define PACHA_FD_FLAG_CLOEXEC (1u << 0)
#define PACHA_FD_FLAG_NONBLOCK (1u << 1)
#define PACHA_FD_FLAG_INHERIT (1u << 2)
#define PACHA_FD_FLAG_PRIVATE (1u << 3)

#define PACHA_FD_EVENT_READABLE (1ull << 0)
#define PACHA_FD_EVENT_WRITABLE (1ull << 1)
#define PACHA_FD_EVENT_ERROR (1ull << 2)
#define PACHA_FD_EVENT_HANGUP (1ull << 3)

#define PACHA_FD_WAIT_FOREVER UINT64_MAX
#define PACHA_TIMERFD_CLOCK_MONOTONIC 1
#define PACHA_TIMERFD_ABSTIME (1ull << 0)

#endif
