#include "dispatch/common.h"

#include "backend.c"
#include "metrics.c"
#include "cache/page_cache.c"
#include "cache/dir_cache.c"
#include "cache/negative_cache.c"
#include "cache/vmo_cache.c"
#include "dispatch/transport_reply.c"
#include "dispatch/ops_common.c"
#include "dispatch/ops_file.c"
#include "dispatch/ops_dir.c"
#include "dispatch/ops_exec.c"
#include "dispatch/transport.c"
