// Keep the Linux ABI server as one translation unit for now: most helpers are
// intentionally file-local, but the implementation is split by subsystem.
#include "common.inc.c"
#include "runtime.inc.c"
#include "vfs.inc.c"
#include "console.inc.c"
#include "process_state.inc.c"
#include "execve.inc.c"
#include "fs_syscalls.inc.c"
#include "fd_syscalls.inc.c"
#include "process_syscalls.inc.c"
#include "futex_syscalls.inc.c"
#include "misc_syscalls.inc.c"
#include "vm_syscalls.inc.c"
#include "main_loop.inc.c"
