schema_version = 1

[app]
id = "resolv_conf"
kind = "file"
role = "asset"

[source.file]
path = "userland/fixtures/base/resolv.conf"

[build]
format = "blob"
target = ""
optimize = "release"
output_name = "RESOLV.CONF"
strip = false

[[publish]]
id = "rootfs"
fs = "rootfs"
path = "/etc/resolv.conf"
