#![no_std]

//! Minimal Wasmtime embedding crate for CapabilityOS.
//!
//! Phase 5B proves that upstream `wasmtime` can be built and linked on top of
//! `rt_wasmtime_platform` with `default-features = false` and the `runtime`
//! feature enabled.
//!
//! Phase 5C adds a loader for precompiled / serialized module artifacts using
//! `cap_std::fs`.

extern crate alloc;

use alloc::string::String;
use alloc::vec::Vec;
use cap_std::fs::RootDir;
use cap_std::io::Read;
use cap_std::path::{Path, PathBuf};
use cap_std::{Error, ErrorKind, Result};
use core::fmt::Write;

pub use wasmtime;

pub const WASMTIME_FEATURE_POLICY: &str = "default-features=false,runtime,pulley";
pub const WASMTIME_TARGET_TRIPLE: &str = "pulley64";

#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub enum PrecompiledKind {
    Module,
    Component,
}

impl PrecompiledKind {
    pub const fn name(self) -> &'static str {
        match self {
            Self::Module => "module",
            Self::Component => "component",
        }
    }
}

#[derive(Clone, Debug)]
pub struct SerializedModuleArtifact {
    path: PathBuf,
    bytes: Vec<u8>,
    kind: PrecompiledKind,
}

impl SerializedModuleArtifact {
    pub fn load_from_root<P>(path: P) -> Result<Self>
    where
        P: AsRef<Path>,
    {
        let root = RootDir::connect_default()?;
        Self::load_from_root_dir(&root, path)
    }

    pub fn load_from_root_dir<P>(root: &RootDir, path: P) -> Result<Self>
    where
        P: AsRef<Path>,
    {
        let path_ref = path.as_ref();
        let mut file = root.open_file(path_ref)?;
        let mut bytes = Vec::new();
        file.read_to_end(&mut bytes)?;
        let kind = detect_precompiled_kind(&bytes)?;
        Ok(Self {
            path: PathBuf::from_path(path_ref),
            bytes,
            kind,
        })
    }

    pub fn path(&self) -> &Path {
        self.path.as_path()
    }

    pub fn len(&self) -> usize {
        self.bytes.len()
    }

    pub fn is_empty(&self) -> bool {
        self.bytes.is_empty()
    }

    pub fn bytes(&self) -> &[u8] {
        &self.bytes
    }

    pub fn precompiled_kind(&self) -> PrecompiledKind {
        self.kind
    }

    pub fn precompiled_kind_name(&self) -> &'static str {
        self.kind.name()
    }

    pub fn deserialize_module(&self, engine: &wasmtime::Engine) -> Result<wasmtime::Module> {
        if self.kind != PrecompiledKind::Module {
            return Err(Error::new(ErrorKind::InvalidData));
        }
        // SAFETY: The loader only accepts bytes that Wasmtime itself identifies
        // as a precompiled artifact. The artifact file is generated by the
        // trusted host-side builder in this repository.
        unsafe { wasmtime::Module::deserialize(engine, &self.bytes) }
            .map_err(|err| map_wasmtime_error("module.deserialize", err))
    }
}

pub fn platform_page_size() -> usize {
    rt_wasmtime_platform::page_size()
}

pub fn smoke_config() -> wasmtime::Config {
    wasmtime::Config::new()
}

fn configure_capabilityos_target(
    config: &mut wasmtime::Config,
) -> core::result::Result<(), wasmtime::Error> {
    config.target(WASMTIME_TARGET_TRIPLE)?;
    config.signals_based_traps(false);
    config.memory_guard_size(0);
    config.memory_reservation(0);
    config.memory_reservation_for_growth(1 << 20);
    config.memory_init_cow(false);
    Ok(())
}

pub fn default_engine() -> Result<wasmtime::Engine> {
    let mut config = smoke_config();
    configure_capabilityos_target(&mut config)
        .map_err(|err| map_wasmtime_error("config.prepare", err))?;
    wasmtime::Engine::new(&config).map_err(|err| map_wasmtime_error("engine.new", err))
}

pub fn call_zero_arg_i32_export(
    engine: &wasmtime::Engine,
    module: &wasmtime::Module,
    export_name: &str,
) -> Result<i32> {
    let mut store = wasmtime::Store::new(engine, ());
    let instance = wasmtime::Instance::new(&mut store, module, &[])
        .map_err(|err| map_wasmtime_error("instance.new", err))?;
    let func = instance
        .get_typed_func::<(), i32>(&mut store, export_name)
        .map_err(|err| map_wasmtime_error("instance.get_typed_func", err))?;
    func.call(&mut store, ())
        .map_err(|err| map_wasmtime_error("typed_func.call", err))
}

fn detect_precompiled_kind(bytes: &[u8]) -> Result<PrecompiledKind> {
    match wasmtime::Engine::detect_precompiled(bytes) {
        Some(wasmtime::Precompiled::Module) => Ok(PrecompiledKind::Module),
        Some(wasmtime::Precompiled::Component) => Ok(PrecompiledKind::Component),
        None => Err(Error::new(ErrorKind::InvalidData)),
    }
}

fn map_wasmtime_error(context: &str, err: wasmtime::Error) -> Error {
    log_wasmtime_error(context, &err);
    Error::new(ErrorKind::Other)
}

fn log_wasmtime_error(context: &str, err: &wasmtime::Error) {
    let mut line = String::from("wasmtime_host: ");
    let _ = write!(&mut line, "{context}: {err}\n");
    cap_std::rt_core::log(&line);
    for (index, cause) in err.chain().enumerate() {
        if index == 0 {
            continue;
        }
        let mut cause_line = String::from("wasmtime_host: cause[");
        let _ = write!(&mut cause_line, "{index}]: {cause}\n");
        cap_std::rt_core::log(&cause_line);
    }
}
