[package]
name = "wasmtime_host"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
cap_std = { path = "../cap_std" }
rt_wasmtime_platform = { path = "../rt_wasmtime_platform" }
wasmtime = { version = "=40.0.4", default-features = false, features = ["runtime", "pulley"] }
