from __future__ import annotations

import subprocess
import struct
from dataclasses import dataclass
from pathlib import Path

from .build import require_nonempty_file
from .config import Workspace
from .disk import ensure_disk, find_partition, image_spec, is_fat, run
from .manifest import ManifestOutputs

BOOTFS_MAGIC = 0x5346_5442
BOOTFS_VERSION = 1
BOOTFS_KIND_REGULAR = 1
BOOTFS_FLAG_EXECUTABLE_HINT = 1 << 0
BOOTFS_DATA_ALIGN = 16
BOOTFS_HEADER = struct.Struct("<IHHQIIQQQQQII4Q")
BOOTFS_ENTRY = struct.Struct("<IHBBQQII2Q")


@dataclass(frozen=True)
class ManifestPair:
    image_path: str
    source_path: Path


@dataclass(frozen=True)
class BootfsSyncResult:
    bootfs_image: Path
    esp_manifest: Path
    disk_image: Path


def sync_bootfs(workspace: Workspace, manifests: ManifestOutputs) -> BootfsSyncResult:
    disk = ensure_disk(workspace)
    pairs = load_manifest_pairs(manifests.bootfs, allow_dirs=False)
    bootfs_image = workspace.artifacts_dir / "bootfs" / "BOOTFS.IMG"
    build_bootfs_image(bootfs_image, pairs)
    esp_manifest = generate_esp_manifest(workspace, bootfs_image, pairs)
    sync_esp(workspace, disk, esp_manifest)
    return BootfsSyncResult(bootfs_image=bootfs_image, esp_manifest=esp_manifest, disk_image=disk)


def build_bootfs_image(output: Path, pairs: list[ManifestPair]) -> None:
    specs = sorted((pair.image_path, pair.source_path, pair.source_path.read_bytes()) for pair in pairs)
    string_table = bytearray()
    path_offsets: list[int] = []
    for image_path, _, _ in specs:
        validate_image_path(image_path)
        path_offsets.append(len(string_table))
        string_table.extend(image_path.encode("utf-8"))

    header_bytes = BOOTFS_HEADER.size
    entry_bytes_total = BOOTFS_ENTRY.size * len(specs)
    entry_table_offset = header_bytes
    string_table_offset = header_bytes + entry_bytes_total
    data_offset = align_up(string_table_offset + len(string_table), BOOTFS_DATA_ALIGN)

    data_offsets = []
    cursor = data_offset
    for _, _, data in specs:
        cursor = align_up(cursor, BOOTFS_DATA_ALIGN)
        data_offsets.append(cursor)
        cursor += len(data)
    image = bytearray(cursor)
    header = BOOTFS_HEADER.pack(
        BOOTFS_MAGIC,
        BOOTFS_VERSION,
        header_bytes,
        len(image),
        len(specs),
        entry_bytes_total,
        entry_table_offset,
        string_table_offset,
        len(string_table),
        data_offset,
        len(image) - data_offset,
        0,
        0,
        0,
        0,
        0,
        0,
    )
    image[0:header_bytes] = header

    for index, ((image_path, _, data), path_offset, item_data_offset) in enumerate(
        zip(specs, path_offsets, data_offsets)
    ):
        entry = BOOTFS_ENTRY.pack(
            path_offset,
            len(image_path.encode("utf-8")),
            BOOTFS_KIND_REGULAR,
            flags_for_path(image_path),
            item_data_offset,
            len(data),
            mode_for_path(image_path),
            0,
            0,
            0,
        )
        start = entry_table_offset + index * BOOTFS_ENTRY.size
        image[start : start + BOOTFS_ENTRY.size] = entry

    image[string_table_offset : string_table_offset + len(string_table)] = string_table
    for (_, _, data), item_data_offset in zip(specs, data_offsets):
        image[item_data_offset : item_data_offset + len(data)] = data

    output.parent.mkdir(parents=True, exist_ok=True)
    if output.exists() and output.read_bytes() == image:
        return
    output.write_bytes(image)


def generate_esp_manifest(workspace: Workspace, bootfs_image: Path, bootfs_pairs: list[ManifestPair]) -> Path:
    bootx64 = workspace.kernel_dir / "zig-out" / "bin" / "EFI" / "BOOT" / "BOOTX64.EFI"
    require_nonempty_file(bootx64, "EFI boot image")

    seed2 = workspace.get_app("seed2_boot")
    initapp = workspace.planned_artifact_path(seed2)
    require_nonempty_file(initapp, "init image")
    require_nonempty_file(bootfs_image, "bootfs image")

    shell = next((pair.source_path for pair in bootfs_pairs if pair.image_path == "/cmd/shell.elf"), None)
    manifest = workspace.manifests_dir / "esp.generated.txt"
    lines = [
        "# Generated by capos. DO NOT EDIT.",
        f"/EFI/BOOT/BOOTX64.EFI={bootx64}",
        f"/EFI/BOOT/INITAPP.ELF={initapp}",
        f"/EFI/BOOT/BOOTFS.IMG={bootfs_image}",
    ]
    if shell is not None and shell.exists():
        lines.insert(2, f"/EFI/BOOT/SHELL.ELF={shell}")
    contents = "\n".join(lines) + "\n"
    manifest.parent.mkdir(parents=True, exist_ok=True)
    if not manifest.exists() or manifest.read_text(encoding="utf-8") != contents:
        manifest.write_text(contents, encoding="utf-8", newline="\n")
    return manifest


def sync_esp(workspace: Workspace, disk: Path, esp_manifest: Path) -> None:
    partition = find_partition(workspace, "esp")
    if not is_fat(partition.config.format):
        raise ValueError(f"ESP partition must be FAT, got {partition.config.format!r}")
    spec = image_spec(disk, partition)
    for directory in ["/EFI", "/EFI/BOOT"]:
        mtools_mkdir(spec, directory, workspace.root)
    for pair in load_manifest_pairs(esp_manifest, allow_dirs=False):
        parent = str(Path(pair.image_path).parent).replace("\\", "/")
        if parent and parent != "/":
            ensure_mtools_dirs(spec, parent, workspace.root)
        run(
            ["mcopy", "-o", "-i", spec, str(pair.source_path), f"::{pair.image_path}"],
            cwd=workspace.root,
            label=f"esp copy {pair.image_path}",
        )


def ensure_mtools_dirs(spec: str, image_dir: str, cwd: Path) -> None:
    current = ""
    for part in image_dir.strip("/").split("/"):
        if not part:
            continue
        current += f"/{part}"
        mtools_mkdir(spec, current, cwd)


def mtools_mkdir(spec: str, image_dir: str, cwd: Path) -> None:
    exists = subprocess.run(
        ["mdir", "-i", spec, f"::{image_dir}"],
        cwd=cwd,
        stdin=subprocess.DEVNULL,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        timeout=10,
    )
    if exists.returncode == 0:
        return
    command = ["mmd", "-i", spec, f"::{image_dir}"]
    completed = subprocess.run(
        command,
        cwd=cwd,
        stdin=subprocess.DEVNULL,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        timeout=10,
    )
    if completed.returncode != 0:
        raise RuntimeError(f"mkdir {image_dir} failed with exit code {completed.returncode}")


def load_manifest_pairs(manifest: Path, *, allow_dirs: bool) -> list[ManifestPair]:
    pairs: list[ManifestPair] = []
    for line_number, raw in enumerate(manifest.read_text(encoding="utf-8").splitlines(), start=1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            raise ValueError(f"{manifest}:{line_number}: invalid manifest line")
        image_path, source = (part.strip() for part in line.split("=", 1))
        if source == "@dir":
            if allow_dirs:
                continue
            raise ValueError(f"{manifest}:{line_number}: directory entry is not allowed: {image_path}")
        source_path = Path(source)
        if not source_path.is_absolute():
            source_path = manifest.parent / source_path
        require_nonempty_file(source_path, f"manifest source {image_path}")
        pairs.append(ManifestPair(image_path=image_path, source_path=source_path))
    return pairs


def validate_image_path(path: str) -> None:
    if len(path) < 2 or not path.startswith("/") or path.endswith("/"):
        raise ValueError(f"invalid bootfs image path: {path!r}")
    if "//" in path or "/./" in path or path.endswith("/.") or "/../" in path or path.endswith("/.."):
        raise ValueError(f"invalid bootfs image path: {path!r}")


def flags_for_path(path: str) -> int:
    return BOOTFS_FLAG_EXECUTABLE_HINT if path.endswith(".elf") else 0


def mode_for_path(path: str) -> int:
    return 0o555 if path.endswith(".elf") else 0o444


def align_up(value: int, alignment: int) -> int:
    return ((value + alignment - 1) // alignment) * alignment
