from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .config import AppDefinition, Workspace


@dataclass(frozen=True)
class ManifestOutputs:
    bootfs: Path
    rootfs: Path
    startup: Path


@dataclass(frozen=True)
class ManifestEntry:
    image_path: str
    source_path: Path | None
    is_dir: bool = False


def generate_manifests(
    workspace: Workspace,
    write: bool = True,
    expand_dirs: bool = True,
) -> ManifestOutputs:
    apps = discover_manifest_apps(workspace)
    startup_contents = render_startup_manifest(apps)
    bootfs_contents = render_fs_manifest("bootfs", workspace, apps, expand_dirs)
    rootfs_contents = render_fs_manifest("rootfs", workspace, apps, expand_dirs)

    if write:
        write_if_changed(workspace.startup_manifest, startup_contents)
        write_if_changed(workspace.bootfs_manifest, bootfs_contents)
        write_if_changed(workspace.rootfs_manifest, rootfs_contents)

    return ManifestOutputs(
        bootfs=workspace.bootfs_manifest,
        rootfs=workspace.rootfs_manifest,
        startup=workspace.startup_manifest,
    )


def discover_manifest_apps(workspace: Workspace) -> list[AppDefinition]:
    selected: list[AppDefinition] = []
    for app in workspace.discover_apps():
        if workspace.app_is_skipped(app):
            if not workspace.include_skipped_artifacts_in_manifests:
                continue
            if not workspace.planned_artifact_path(app).exists():
                continue
        selected.append(app)
    return selected


def render_fs_manifest(
    fs_name: str,
    workspace: Workspace,
    apps: list[AppDefinition],
    expand_dirs: bool,
) -> str:
    entries: list[ManifestEntry] = []
    for entry in workspace.publish_dirs:
        if entry.get("fs") == fs_name:
            entries.append(ManifestEntry(str(entry.get("path", "")), None, True))

    for app in apps:
        source = workspace.planned_artifact_path(app)
        for publish in app.publish:
            if publish.fs != fs_name:
                continue
            if source.is_dir() and expand_dirs:
                entries.extend(directory_entries(publish.path, source))
            elif source.is_dir():
                entries.append(ManifestEntry(publish.path, source, True))
            else:
                entries.append(ManifestEntry(publish.path, source, False))

    if fs_name in workspace.startup_manifest_include:
        entries.append(ManifestEntry(workspace.startup_manifest_path, workspace.startup_manifest, False))

    dirs = sorted((entry for entry in entries if entry.is_dir), key=lambda item: item.image_path)
    files = sorted((entry for entry in entries if not entry.is_dir), key=lambda item: item.image_path)
    ordered = dirs + files

    seen: dict[str, ManifestEntry] = {}
    lines = ["# Generated by capos. DO NOT EDIT."]
    for entry in ordered:
        previous = seen.get(entry.image_path)
        if previous is not None:
            if previous.is_dir and entry.is_dir:
                continue
            raise ValueError(f"duplicate {fs_name} publish path: {entry.image_path}")
        seen[entry.image_path] = entry
        if entry.is_dir:
            lines.append(f"{entry.image_path}=@dir")
        elif entry.source_path is not None:
            lines.append(f"{entry.image_path}={entry.source_path}")
        else:
            raise ValueError(f"missing source for {entry.image_path}")
    return "\n".join(lines) + "\n"


def directory_entries(image_root: str, source_root: Path) -> list[ManifestEntry]:
    out: list[ManifestEntry] = [ManifestEntry(image_root, None, True)]
    for child in sorted(source_root.rglob("*")):
        rel = child.relative_to(source_root).as_posix()
        image_path = join_image_path(image_root, rel)
        if child.is_dir():
            out.append(ManifestEntry(image_path, None, True))
        elif child.is_file():
            out.append(ManifestEntry(image_path, child, False))
    return out


def join_image_path(root: str, relative: str) -> str:
    root = root.rstrip("/")
    relative = relative.lstrip("/")
    if not root:
        return f"/{relative}"
    if not relative:
        return root
    return f"{root}/{relative}"


def render_startup_manifest(apps: list[AppDefinition]) -> str:
    nodes = []
    names: set[str] = set()
    for app in apps:
        if not app.startup:
            continue
        startup = app.startup
        publish_id = str(startup.get("publish", ""))
        publish = next((entry for entry in app.publish if entry.id == publish_id), None)
        if publish is None:
            raise ValueError(f"{app.app_id}: startup.publish references missing publish entry {publish_id}")
        name = str(startup.get("name", ""))
        if name in names:
            raise ValueError(f"duplicate startup name: {name}")
        names.add(name)
        nodes.append((app, startup, publish))

    emitted: set[str] = set()
    ordered = []
    pending = sorted(nodes, key=lambda item: str(item[1].get("name", "")))
    while pending:
        index = next(
            (
                i
                for i, (_, startup, _) in enumerate(pending)
                if all(dep in emitted for dep in startup.get("after", []))
            ),
            None,
        )
        if index is None:
            cycle = ", ".join(str(startup.get("name", "")) for _, startup, _ in pending)
            raise ValueError(f"startup dependency cycle detected: {cycle}")
        item = pending.pop(index)
        emitted.add(str(item[1].get("name", "")))
        ordered.append(item)

    lines = ["# Generated by capos. DO NOT EDIT."]
    for app, startup, publish in ordered:
        parts = [
            f"action={startup.get('action', '')}",
            f"name={startup.get('name', '')}",
            f"path={publish.path}",
            f"label={startup.get('label', '')}",
            f"load={startup.get('load', '')}",
        ]
        for singleton in ("block", "input", "device"):
            values = startup.get(singleton, [])
            if values:
                if len(values) != 1:
                    raise ValueError(f"{app.app_id}: startup {singleton} selector must have exactly one value")
                parts.append(f"{singleton}={values[0]}")
        for list_key in ("after", "requires", "ensure", "provides"):
            values = startup.get(list_key, [])
            if values:
                parts.append(f"{list_key}={','.join(values)}")
        lines.append(" ".join(parts))
    return "\n".join(lines) + "\n"


def write_if_changed(path: Path, contents: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == contents:
        return
    path.write_text(contents, encoding="utf-8", newline="\n")
