#!/usr/bin/env python3

import argparse
import struct
from pathlib import Path

from PIL import Image


DEFAULT_INPUT = Path("PachaOSLogo/logo.png")
DEFAULT_OUTPUT_ZIG = Path("bootstrap/programs/generated_pacha_logo.zig")
DEFAULT_OUTPUT_BIN = Path("bootstrap/programs/generated_pacha_logo.bin")
DEFAULT_BG_THRESHOLD_LOW = 5
DEFAULT_BG_THRESHOLD_HIGH = 48


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert a PNG logo into an embedded framebuffer-friendly boot asset."
    )
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT, help="Source PNG path.")
    parser.add_argument(
        "--output-zig",
        type=Path,
        default=DEFAULT_OUTPUT_ZIG,
        help="Output Zig metadata file path.",
    )
    parser.add_argument(
        "--output-bin",
        type=Path,
        default=DEFAULT_OUTPUT_BIN,
        help="Output packed pixel binary path.",
    )
    parser.add_argument("--max-width", type=int, default=320, help="Maximum output width.")
    parser.add_argument("--max-height", type=int, default=110, help="Maximum output height.")
    parser.add_argument(
        "--bg-threshold-low",
        type=int,
        default=DEFAULT_BG_THRESHOLD_LOW,
        help="Color distance at or below this value becomes fully transparent.",
    )
    parser.add_argument(
        "--bg-threshold-high",
        type=int,
        default=DEFAULT_BG_THRESHOLD_HIGH,
        help="Color distance at or above this value becomes fully opaque.",
    )
    return parser.parse_args()


def resize_to_fit(image: Image.Image, max_width: int, max_height: int) -> Image.Image:
    if max_width <= 0 or max_height <= 0:
        raise ValueError("max dimensions must be positive")
    if image.width <= max_width and image.height <= max_height:
        return image
    scale = min(max_width / image.width, max_height / image.height)
    resized_width = max(1, round(image.width * scale))
    resized_height = max(1, round(image.height * scale))
    return image.resize((resized_width, resized_height), Image.Resampling.LANCZOS)


def sample_background_color(image: Image.Image) -> tuple[int, int, int]:
    rgba = image.convert("RGBA")
    width, height = rgba.size
    corners = [
        rgba.getpixel((0, 0)),
        rgba.getpixel((width - 1, 0)),
        rgba.getpixel((0, height - 1)),
        rgba.getpixel((width - 1, height - 1)),
    ]
    return tuple(sum(pixel[channel] for pixel in corners) // len(corners) for channel in range(3))


def clamp_u8(value: float) -> int:
    return max(0, min(255, int(round(value))))


def key_alpha(distance: int, threshold_low: int, threshold_high: int) -> int:
    if distance <= threshold_low:
        return 0
    if distance >= threshold_high:
        return 255
    return ((distance - threshold_low) * 255) // (threshold_high - threshold_low)


def remove_background(image: Image.Image, threshold_low: int, threshold_high: int) -> Image.Image:
    if threshold_low < 0 or threshold_high <= threshold_low:
        raise ValueError("background thresholds must satisfy 0 <= low < high")

    rgba = image.convert("RGBA")
    bg_r, bg_g, bg_b = sample_background_color(rgba)
    raw = bytearray(rgba.tobytes())
    keyed = bytearray(len(raw))

    for offset in range(0, len(raw), 4):
        src_r = raw[offset]
        src_g = raw[offset + 1]
        src_b = raw[offset + 2]
        src_a = raw[offset + 3]
        distance = max(abs(src_r - bg_r), abs(src_g - bg_g), abs(src_b - bg_b))
        bg_alpha = key_alpha(distance, threshold_low, threshold_high)
        out_a = (src_a * bg_alpha) // 255
        if out_a == 0:
            continue

        if bg_alpha == 255:
            keyed[offset] = src_r
            keyed[offset + 1] = src_g
            keyed[offset + 2] = src_b
            keyed[offset + 3] = out_a
            continue

        alpha = bg_alpha / 255.0
        keyed[offset] = clamp_u8((src_r - bg_r * (1.0 - alpha)) / alpha)
        keyed[offset + 1] = clamp_u8((src_g - bg_g * (1.0 - alpha)) / alpha)
        keyed[offset + 2] = clamp_u8((src_b - bg_b * (1.0 - alpha)) / alpha)
        keyed[offset + 3] = out_a

    return Image.frombytes("RGBA", rgba.size, bytes(keyed))


def emit_binary(image: Image.Image, output_path: Path) -> None:
    rgba = image.convert("RGBA")
    raw = rgba.tobytes()
    packed = bytearray(len(raw))
    for offset in range(0, len(raw), 4):
        r = raw[offset]
        g = raw[offset + 1]
        b = raw[offset + 2]
        a = raw[offset + 3]
        struct.pack_into("<I", packed, offset, (a << 24) | (r << 16) | (g << 8) | b)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_bytes(packed)


def emit_zig(source_path: Path, output_zig: Path, output_bin: Path, width: int, height: int) -> None:
    bin_name = output_bin.name.replace("\\", "/")
    lines = [
        "// Generated by tools/logo_to_fb.py. Do not edit manually.",
        f'pub const source_png = "{source_path.as_posix()}";',
        f"pub const width: usize = {width};",
        f"pub const height: usize = {height};",
        "pub const pixel_count: usize = width * height;",
        f'pub const pixel_bytes = @embedFile("{bin_name}");',
        "",
        "pub fn packedPixel(index: usize) u32 {",
        "    const offset = index * 4;",
        "    return @as(u32, pixel_bytes[offset]) |",
        "        (@as(u32, pixel_bytes[offset + 1]) << 8) |",
        "        (@as(u32, pixel_bytes[offset + 2]) << 16) |",
        "        (@as(u32, pixel_bytes[offset + 3]) << 24);",
        "}",
        "",
    ]
    output_zig.parent.mkdir(parents=True, exist_ok=True)
    output_zig.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    args = parse_args()
    if not args.input.is_file():
        raise FileNotFoundError(f"PNG not found: {args.input}")

    image = Image.open(args.input)
    image = resize_to_fit(image, args.max_width, args.max_height)
    image = remove_background(image, args.bg_threshold_low, args.bg_threshold_high)
    emit_binary(image, args.output_bin)
    emit_zig(args.input, args.output_zig, args.output_bin, image.width, image.height)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
