[package]
name = "rust_wasmtime_trap_demo"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "rust_wasmtime_trap_demo"
path = "src/main.rs"

[dependencies]
cap_std = { path = "../../../user/rust/cap_std" }
rt_alloc = { path = "../../../user/rust/rt_alloc" }
wasmtime_host = { path = "../../../user/rust/wasmtime_host" }
