#ifndef PERSONALITY_LINUX_LPR_H
#define PERSONALITY_LINUX_LPR_H

#include <stddef.h>
#include <stdint.h>
#include <pacha/status.h>
#include "lpr_image_abi.h"
#include "lpr_manifest.h"
#include "personality_abi.h"
#include "runtime_page.h"

#define LPR_LINUX_SYS_READ 0ull
#define LPR_LINUX_SYS_WRITE 1ull
#define LPR_LINUX_SYS_OPEN 2ull
#define LPR_LINUX_SYS_CLOSE 3ull
#define LPR_LINUX_SYS_STAT 4ull
#define LPR_LINUX_SYS_FSTAT 5ull
#define LPR_LINUX_SYS_LSTAT 6ull
#define LPR_LINUX_SYS_POLL 7ull
#define LPR_LINUX_SYS_LSEEK 8ull
#define LPR_LINUX_SYS_MMAP 9ull
#define LPR_LINUX_SYS_MPROTECT 10ull
#define LPR_LINUX_SYS_MUNMAP 11ull
#define LPR_LINUX_SYS_BRK 12ull
#define LPR_LINUX_SYS_RT_SIGACTION 13ull
#define LPR_LINUX_SYS_RT_SIGPROCMASK 14ull
#define LPR_LINUX_SYS_RT_SIGRETURN 15ull
#define LPR_LINUX_SYS_IOCTL 16ull
#define LPR_LINUX_SYS_PREAD64 17ull
#define LPR_LINUX_SYS_READV 19ull
#define LPR_LINUX_SYS_WRITEV 20ull
#define LPR_LINUX_SYS_ACCESS 21ull
#define LPR_LINUX_SYS_PIPE 22ull
#define LPR_LINUX_SYS_SELECT 23ull
#define LPR_LINUX_SYS_MREMAP 25ull
#define LPR_LINUX_SYS_MSYNC 26ull
#define LPR_LINUX_SYS_DUP 32ull
#define LPR_LINUX_SYS_DUP2 33ull
#define LPR_LINUX_SYS_NANOSLEEP 35ull
#define LPR_LINUX_SYS_GETITIMER 36ull
#define LPR_LINUX_SYS_SETITIMER 38ull
#define LPR_LINUX_SYS_GETPID 39ull
#define LPR_LINUX_SYS_KILL 62ull
#define LPR_LINUX_SYS_SOCKET 41ull
#define LPR_LINUX_SYS_CONNECT 42ull
#define LPR_LINUX_SYS_ACCEPT 43ull
#define LPR_LINUX_SYS_SENDTO 44ull
#define LPR_LINUX_SYS_RECVFROM 45ull
#define LPR_LINUX_SYS_SENDMSG 46ull
#define LPR_LINUX_SYS_RECVMSG 47ull
#define LPR_LINUX_SYS_SHUTDOWN 48ull
#define LPR_LINUX_SYS_BIND 49ull
#define LPR_LINUX_SYS_LISTEN 50ull
#define LPR_LINUX_SYS_GETSOCKNAME 51ull
#define LPR_LINUX_SYS_GETPEERNAME 52ull
#define LPR_LINUX_SYS_SOCKETPAIR 53ull
#define LPR_LINUX_SYS_SETSOCKOPT 54ull
#define LPR_LINUX_SYS_GETSOCKOPT 55ull
#define LPR_LINUX_SYS_CLONE 56ull
#define LPR_LINUX_SYS_UNAME 63ull
#define LPR_LINUX_SYS_FORK 57ull
#define LPR_LINUX_SYS_VFORK 58ull
#define LPR_LINUX_SYS_EXECVE 59ull
#define LPR_LINUX_SYS_EXIT 60ull
#define LPR_LINUX_SYS_WAIT4 61ull
#define LPR_LINUX_SYS_FCNTL 72ull
#define LPR_LINUX_SYS_FLOCK 73ull
#define LPR_LINUX_SYS_FSYNC 74ull
#define LPR_LINUX_SYS_FDATASYNC 75ull
#define LPR_LINUX_SYS_FTRUNCATE 77ull
#define LPR_LINUX_SYS_GETCWD 79ull
#define LPR_LINUX_SYS_CHDIR 80ull
#define LPR_LINUX_SYS_FCHDIR 81ull
#define LPR_LINUX_SYS_RENAME 82ull
#define LPR_LINUX_SYS_MKDIR 83ull
#define LPR_LINUX_SYS_RMDIR 84ull
#define LPR_LINUX_SYS_LINK 86ull
#define LPR_LINUX_SYS_UNLINK 87ull
#define LPR_LINUX_SYS_SYMLINK 88ull
#define LPR_LINUX_SYS_READLINK 89ull
#define LPR_LINUX_SYS_CHMOD 90ull
#define LPR_LINUX_SYS_FCHMOD 91ull
#define LPR_LINUX_SYS_CHOWN 92ull
#define LPR_LINUX_SYS_FCHOWN 93ull
#define LPR_LINUX_SYS_LCHOWN 94ull
#define LPR_LINUX_SYS_UMASK 95ull
#define LPR_LINUX_SYS_GETRLIMIT 97ull
#define LPR_LINUX_SYS_SYSINFO 99ull
#define LPR_LINUX_SYS_GETUID 102ull
#define LPR_LINUX_SYS_GETGID 104ull
#define LPR_LINUX_SYS_SETUID 105ull
#define LPR_LINUX_SYS_SETGID 106ull
#define LPR_LINUX_SYS_GETEUID 107ull
#define LPR_LINUX_SYS_GETEGID 108ull
#define LPR_LINUX_SYS_SETPGID 109ull
#define LPR_LINUX_SYS_GETPPID 110ull
#define LPR_LINUX_SYS_GETPGRP 111ull
#define LPR_LINUX_SYS_SETSID 112ull
#define LPR_LINUX_SYS_SETRESUID 117ull
#define LPR_LINUX_SYS_GETRESUID 118ull
#define LPR_LINUX_SYS_SETRESGID 119ull
#define LPR_LINUX_SYS_GETRESGID 120ull
#define LPR_LINUX_SYS_GETPGID 121ull
#define LPR_LINUX_SYS_GETSID 124ull
#define LPR_LINUX_SYS_CAPGET 125ull
#define LPR_LINUX_SYS_CAPSET 126ull
#define LPR_LINUX_SYS_RT_SIGPENDING 127ull
#define LPR_LINUX_SYS_RT_SIGTIMEDWAIT 128ull
#define LPR_LINUX_SYS_RT_SIGSUSPEND 130ull
#define LPR_LINUX_SYS_SIGALTSTACK 131ull
#define LPR_LINUX_SYS_STATFS 137ull
#define LPR_LINUX_SYS_FSTATFS 138ull
#define LPR_LINUX_SYS_SETPRIORITY 141ull
#define LPR_LINUX_SYS_SETRLIMIT 160ull
#define LPR_LINUX_SYS_SYNC 162ull
#define LPR_LINUX_SYS_ARCH_PRCTL 158ull
#define LPR_LINUX_SYS_PRCTL 157ull
#define LPR_LINUX_SYS_GETTID 186ull
#define LPR_LINUX_SYS_TKILL 200ull
#define LPR_LINUX_SYS_FUTEX 202ull
#define LPR_LINUX_SYS_SCHED_GETAFFINITY 204ull
#define LPR_LINUX_SYS_GETDENTS64 217ull
#define LPR_LINUX_SYS_SET_TID_ADDRESS 218ull
#define LPR_LINUX_SYS_FADVISE64 221ull
#define LPR_LINUX_SYS_CLOCK_GETTIME 228ull
#define LPR_LINUX_SYS_CLOCK_GETRES 229ull
#define LPR_LINUX_SYS_CLOCK_NANOSLEEP 230ull
#define LPR_LINUX_SYS_EXIT_GROUP 231ull
#define LPR_LINUX_SYS_EPOLL_WAIT 232ull
#define LPR_LINUX_SYS_EPOLL_CTL 233ull
#define LPR_LINUX_SYS_TGKILL 234ull
#define LPR_LINUX_SYS_INOTIFY_INIT 253ull
#define LPR_LINUX_SYS_INOTIFY_ADD_WATCH 254ull
#define LPR_LINUX_SYS_INOTIFY_RM_WATCH 255ull
#define LPR_LINUX_SYS_OPENAT 257ull
#define LPR_LINUX_SYS_MKDIRAT 258ull
#define LPR_LINUX_SYS_MKNODAT 259ull
#define LPR_LINUX_SYS_FCHOWNAT 260ull
#define LPR_LINUX_SYS_NEWFSTATAT 262ull
#define LPR_LINUX_SYS_UNLINKAT 263ull
#define LPR_LINUX_SYS_RENAMEAT 264ull
#define LPR_LINUX_SYS_LINKAT 265ull
#define LPR_LINUX_SYS_FCHMODAT 268ull
#define LPR_LINUX_SYS_FACCESSAT 269ull
#define LPR_LINUX_SYS_SYMLINKAT 266ull
#define LPR_LINUX_SYS_UNSHARE 272ull
#define LPR_LINUX_SYS_PSELECT6 270ull
#define LPR_LINUX_SYS_PPOLL 271ull
#define LPR_LINUX_SYS_UTIMENSAT 280ull
#define LPR_LINUX_SYS_EPOLL_PWAIT 281ull
#define LPR_LINUX_SYS_TIMERFD_CREATE 283ull
#define LPR_LINUX_SYS_EVENTFD 284ull
#define LPR_LINUX_SYS_TIMERFD_SETTIME 286ull
#define LPR_LINUX_SYS_TIMERFD_GETTIME 287ull
#define LPR_LINUX_SYS_SIGNALFD4 289ull
#define LPR_LINUX_SYS_EVENTFD2 290ull
#define LPR_LINUX_SYS_EPOLL_CREATE1 291ull
#define LPR_LINUX_SYS_DUP3 292ull
#define LPR_LINUX_SYS_PIPE2 293ull
#define LPR_LINUX_SYS_INOTIFY_INIT1 294ull
#define LPR_LINUX_SYS_CLOSE_RANGE 436ull
#define LPR_LINUX_SYS_RECVMMSG 299ull
#define LPR_LINUX_SYS_PRLIMIT64 302ull
#define LPR_LINUX_SYS_SYNCFS 306ull
#define LPR_LINUX_SYS_SENDMMSG 307ull
#define LPR_LINUX_SYS_GETRANDOM 318ull
#define LPR_LINUX_SYS_MEMFD_CREATE 319ull
#define LPR_LINUX_SYS_MEMBARRIER 324ull
#define LPR_LINUX_SYS_STATX 332ull
#define LPR_LINUX_SYS_FALLOCATE 285ull
#define LPR_LINUX_SYS_FACCESSAT2 439ull
#define LPR_LINUX_SYS_LAST LPR_LINUX_SYS_FACCESSAT2

#define LPR_LINUX_FD_MAX 0x7fffffffull
#define LPR_LINUX_FD_LIMIT (LPR_LINUX_FD_MAX + 1ull)

#define LPR_LINUX_ARCH_SET_GS 0x1001ull
#define LPR_LINUX_ARCH_SET_FS 0x1002ull
#define LPR_LINUX_ARCH_GET_FS 0x1003ull
#define LPR_LINUX_ARCH_GET_GS 0x1004ull

int64_t lpr_start(struct lpr_runtime_page *runtime);

#endif
