#ifndef PERSONALITY_LPR_SIGNAL_STACK_H
#define PERSONALITY_LPR_SIGNAL_STACK_H

#define LPR_SYSCALL_ENTRY_FRAME_BYTES 328
#define LPR_NATIVE_SIGNAL_RED_ZONE_BYTES 128
#define LPR_NATIVE_SIGNAL_FRAME_BYTES 1024
#define LPR_NATIVE_SIGNAL_RUNTIME_STACK_BYTES 4096
#define LPR_NATIVE_SIGNAL_WORK_STACK_BYTES 4096
#define LPR_SYSCALL_ENTRY_RESERVE_BYTES \
    (LPR_SYSCALL_ENTRY_FRAME_BYTES + LPR_NATIVE_SIGNAL_RED_ZONE_BYTES + \
     LPR_NATIVE_SIGNAL_FRAME_BYTES + LPR_NATIVE_SIGNAL_RUNTIME_STACK_BYTES + \
     LPR_NATIVE_SIGNAL_WORK_STACK_BYTES)

#endif
