schema_version = 1

[app]
id = "busybox"
kind = "file"
role = "asset"

[source.file]
path = "userland/fixtures/busybox.elf"
rebuild_tool = "wsl"
rebuild_dir = "."
rebuild_args = ["-e", "bash", "tools/build_wsl_busybox.sh"]

[build]
format = "blob"
target = ""
optimize = "release"
output_name = "BUSYBOX.ELF"
strip = false

[[publish]]
id = "rootfs"
fs = "rootfs"
path = "/cmd/busybox.elf"

[[publish]]
id = "bin_busybox"
fs = "rootfs"
path = "/bin/busybox"

[[publish]]
id = "bin_ls"
fs = "rootfs"
path = "/bin/ls"

[[publish]]
id = "bin_cat"
fs = "rootfs"
path = "/bin/cat"

[[publish]]
id = "bin_echo"
fs = "rootfs"
path = "/bin/echo"

[[publish]]
id = "bin_pwd"
fs = "rootfs"
path = "/bin/pwd"

[[publish]]
id = "bin_true"
fs = "rootfs"
path = "/bin/true"

[[publish]]
id = "bin_false"
fs = "rootfs"
path = "/bin/false"

[[publish]]
id = "bin_sh"
fs = "rootfs"
path = "/bin/sh"
